---
builds:
  0c8ce7758dce546dfaed59e89ef5a5a7a2f1d6ab:
    version: 0c8ce7758dce546dfaed59e89ef5a5a7a2f1d6ab
    sha1: d5df387ba1a480154b8098a01dae8f323e60699f
    blobstore_id: 18b1c0a9-f7ba-4e24-b858-d4f18aed4cea
  d40d9c06ca2a994a904841c8b7bda399a9a751db:
    version: d40d9c06ca2a994a904841c8b7bda399a9a751db
    sha1: 3a475d288fd13a3987b2b834ca98dbf299550131
    blobstore_id: ec41736f-be0b-4fb2-a2d3-3026111a6381
  780312fde58728287e75b2ef3723cc5496f57ed2:
    version: 780312fde58728287e75b2ef3723cc5496f57ed2
    sha1: 9b970ffb45d3944007626ca493c804182b5c1bf1
    blobstore_id: 25a4299f-468d-47e7-a622-071c37f2b34d
  7924803eb0faad0f47d81bc9fe8abbd5ef772c08:
    version: 7924803eb0faad0f47d81bc9fe8abbd5ef772c08
    sha1: 3061324a807388d9c10b5bfec3123496ab8dc37c
    blobstore_id: d9f870ad-7552-4fb8-82b8-3fb4fa927456
  1a7521699ce572f877ade335534915f6aae2f609:
    version: 1a7521699ce572f877ade335534915f6aae2f609
    sha1: 308fba2fa267f29288e1817b9dd6b92dcf792ae0
    blobstore_id: 486d491b-cf38-4431-84ea-eb0dab8af004
  268988197a95340ac17f7b7018788f87380d8ce2:
    version: 268988197a95340ac17f7b7018788f87380d8ce2
    sha1: 61dd361ae3e7e864de1d47bacab3be90775549d7
    blobstore_id: 6942f994-0b36-4d5d-8361-fbdc24b1e672
  e4ba2544c1adc9f54121cdbce699011c805bc985:
    version: e4ba2544c1adc9f54121cdbce699011c805bc985
    sha1: 443a86823f2855a456e3e09eabbab73996ce4961
    blobstore_id: 591db7e7-c4a9-4529-9c29-d1978db1ba09
  b000e3e0740572b1882e291df76579fe5911c184:
    version: b000e3e0740572b1882e291df76579fe5911c184
    sha1: 3b2859d54756624b72a407a75d8a07ec76a4fd98
    blobstore_id: 394879af-4d16-4c56-86d8-ab331d16e336
  b2d43b89ee4f217df34e2247ccedf63358d2b4a6:
    version: b2d43b89ee4f217df34e2247ccedf63358d2b4a6
    sha1: 8ea3eda5670d31460d1cbafd09cc62f5523c6ab1
    blobstore_id: 9bfaab80-00c0-4c54-ae92-a49882393cb2
format-version: '2'
