---
builds:
  3e497906-3625-4f7a-a2ac-4565cef68561:
    version: '1'
  a9506927-8b43-4a73-8d63-4923855a7a7c:
    version: '2'
  09786c88-7c96-4a44-a627-883e32994b1a:
    version: '3'
  14a4ab0b-dab1-4e35-a8bb-e2bedc0831bb:
    version: '4'
  15ab5e65-ddc0-409b-a71f-91b1978c57f8:
    version: '5'
  7d33496e-a5f4-4b3f-98d6-9ec11116b907:
    version: '6'
  e68dccdf-edb7-4bf2-89ea-0920538c1d17:
    version: '7'
  2d5f328f-50bf-4caf-9428-7ac8a491fa53:
    version: '8'
  2a9a9b98-0aa5-4f6b-9291-0e4f6d09add5:
    version: '9'
  2d40cc21-1c6e-47e7-80f2-8add0bc532e6:
    version: '10'
  b52c1d9f-5563-4443-b9e9-37485cd1341b:
    version: '11'
  975ab641-042c-495b-98b5-e26e525dcbe0:
    version: 12.0.0
  cd353fe7-f442-468f-98d5-b4286ab2b3c5:
    version: 12.0.1
  bc18c515-4693-4d35-ac8f-d271abdbdd86:
    version: 12.1.0
  c1d587eb-0ae9-400c-97be-b1d20e37de6a:
    version: 12.2.0
  95827d8b-64c5-40a8-b5be-90668df71c27:
    version: 12.3.0
  61e82bf3-6ed7-4aaa-b953-5c4261ea6705:
    version: 12.3.1
  e20c16a4-0b76-4717-89cf-129fb53a1cbb:
    version: 12.3.2
  70422302-22ee-4908-a648-2bc7880bac2e:
    version: 12.3.3
  84f79a57-128b-484a-b27a-d1367928b909:
    version: 13.0.0
  f78c30ac-97a7-49c0-a209-d0ec59f9ecca:
    version: 14.0.0
  66f2fb55-24e0-45ac-992b-7afb84142e48:
    version: 15.0.0
  c0f78da0-fa24-4aea-aa50-5334a0508965:
    version: 15.1.0
  5aa141ad-cbcb-4e82-aa1d-234506c914b3:
    version: 15.2.0
  f1fbf245-85de-490a-a08c-2888de40b315:
    version: 15.2.1
  a8191591-4ba9-4323-b8cd-1e996aea96fb:
    version: 15.2.2
  f0106036-1b33-407c-9036-e3e02bb21940:
    version: 16.0.0
  d61122be-7f14-4688-bf12-880629a6423f:
    version: 16.0.1
  e7c84487-9018-430b-b500-0102a36eef12:
    version: 16.0.2
  4b47c1b9-16fd-497d-97b9-2316b68fbbee:
    version: 16.1.0
  170690f8-7cc7-497d-ba9f-12d2c20336c8:
    version: 17.0.0
  55b06794-329e-435b-818f-3f3b39cd03d6:
    version: 17.1.0
  86390599-0f2d-4349-a7f1-3e6fdf36bb0c:
    version: 17.2.0
  f593de39-06dd-417b-b954-8cc72b66b1de:
    version: 17.3.0
  11d8d428-54e8-4cd3-8daf-38bc8fc5e07d:
    version: 17.4.0
  41e4c9c1-231d-4522-a702-61aaa6f6f7a5:
    version: 17.4.1
  1916ce73-d54a-427e-b3e8-aa527bbbb30e:
    version: 17.4.2
  b801bd23-336f-41aa-904c-13d1eebb3b61:
    version: 17.5.0
  629da53c-752e-44c8-aca8-52ab33d5764d:
    version: 17.6.0
format-version: '2'
