---
builds:
  3e497906-3625-4f7a-a2ac-4565cef68561:
    version: '1'
  a9506927-8b43-4a73-8d63-4923855a7a7c:
    version: '2'
  09786c88-7c96-4a44-a627-883e32994b1a:
    version: '3'
  14a4ab0b-dab1-4e35-a8bb-e2bedc0831bb:
    version: '4'
  15ab5e65-ddc0-409b-a71f-91b1978c57f8:
    version: '5'
  7d33496e-a5f4-4b3f-98d6-9ec11116b907:
    version: '6'
  e68dccdf-edb7-4bf2-89ea-0920538c1d17:
    version: '7'
  2d5f328f-50bf-4caf-9428-7ac8a491fa53:
    version: '8'
  2a9a9b98-0aa5-4f6b-9291-0e4f6d09add5:
    version: '9'
  2d40cc21-1c6e-47e7-80f2-8add0bc532e6:
    version: '10'
  b52c1d9f-5563-4443-b9e9-37485cd1341b:
    version: '11'
  975ab641-042c-495b-98b5-e26e525dcbe0:
    version: 12.0.0
  cd353fe7-f442-468f-98d5-b4286ab2b3c5:
    version: 12.0.1
  bc18c515-4693-4d35-ac8f-d271abdbdd86:
    version: 12.1.0
  c1d587eb-0ae9-400c-97be-b1d20e37de6a:
    version: 12.2.0
  95827d8b-64c5-40a8-b5be-90668df71c27:
    version: 12.3.0
  61e82bf3-6ed7-4aaa-b953-5c4261ea6705:
    version: 12.3.1
  e20c16a4-0b76-4717-89cf-129fb53a1cbb:
    version: 12.3.2
  70422302-22ee-4908-a648-2bc7880bac2e:
    version: 12.3.3
  84f79a57-128b-484a-b27a-d1367928b909:
    version: 13.0.0
  f78c30ac-97a7-49c0-a209-d0ec59f9ecca:
    version: 14.0.0
  66f2fb55-24e0-45ac-992b-7afb84142e48:
    version: 15.0.0
  c0f78da0-fa24-4aea-aa50-5334a0508965:
    version: 15.1.0
  5aa141ad-cbcb-4e82-aa1d-234506c914b3:
    version: 15.2.0
  f1fbf245-85de-490a-a08c-2888de40b315:
    version: 15.2.1
format-version: '2'
