---
builds:
  db160098c5c6f49383b28439c4dbb28c6fede263:
    version: db160098c5c6f49383b28439c4dbb28c6fede263
    sha1: 5611a27878811caa06c96e6f28133da264b8e66c
    blobstore_id: 7e04de4f-7338-466d-95e1-9a2591c7d7ae
  2f0b55f644f2eb5a58c322a20d352073bedb7881:
    version: 2f0b55f644f2eb5a58c322a20d352073bedb7881
    sha1: 525f62e278eb7e85f5119585d039324225983880
    blobstore_id: f188dd93-c8a2-409e-8df5-fa4eb338d10b
  452d7a2c72987eee4df435246d56cd958051a062:
    version: 452d7a2c72987eee4df435246d56cd958051a062
    sha1: a7d34aa402bba04b48525885098173960591a5ca
    blobstore_id: dae16b0f-c1e8-44b9-8651-ec5ef383027c
  d0dbe3b9c053c766f500675392ac0db7d7a255a3:
    version: d0dbe3b9c053c766f500675392ac0db7d7a255a3
    sha1: 99e2a975e5d1a81560c24d6066fa90b3ca0b8dbf
    blobstore_id: 66e5832b-9b56-4676-9780-510638dfbe28
  8e568bc097fd82faa378d762a828182914d4c00b:
    version: 8e568bc097fd82faa378d762a828182914d4c00b
    sha1: a210ed8a77608069ae72a0995321e4e7cc2ea804
    blobstore_id: 88a9b5f3-e30f-493a-a4e9-633b8c2ff30e
  3d0e7a51b69473cbb0b7fefcd16768d89081c9da:
    version: 3d0e7a51b69473cbb0b7fefcd16768d89081c9da
    sha1: 24f0c52bdab53a9800c7bb33288f97e8bd4d7677
    blobstore_id: 5e4f64f3-1235-4d74-b467-3be8eee47a02
  85c1273908951c8daeac902d01437bb867dc92e9:
    version: 85c1273908951c8daeac902d01437bb867dc92e9
    sha1: 5447aed8855acd16402b76328cd405a50f9b78f4
    blobstore_id: 7543b1f3-64d9-4c6b-b2ae-19357c15c31d
format-version: '2'
