builds:
  03496b762f4af51817ff874eecc021d92514dc69:
    version: 03496b762f4af51817ff874eecc021d92514dc69
    blobstore_id: 9d9bbee7-fdc1-463a-a0a1-3730885e849c
    sha1: 90a4fb01a2b1640fbf062cd7be884457963641e6
  066d34e18d36329c47456dbb678009e60036bf64:
    version: 066d34e18d36329c47456dbb678009e60036bf64
    blobstore_id: c30cc7f2-3724-429f-9067-3c8e17e9b90f
    sha1: 2e17615e9de66e492c79b3f48f3b608755717e3f
  0b58ae7c9e53bc0f8cf407dce1c59cab039ceab4:
    version: 0b58ae7c9e53bc0f8cf407dce1c59cab039ceab4
    blobstore_id: 102a8ea9-0f58-4e1f-438f-dfad53ce762a
    sha1: 855bad6ffacdd719f4c68fbd216892495b20f56b
  6301a2d247c54c4617ef0bb809c2f5aad885738b:
    version: 6301a2d247c54c4617ef0bb809c2f5aad885738b
    blobstore_id: 61da8418-4d1a-45c9-b44c-6296ce5f6d0d
    sha1: dc9aeb80e7483461c4de2933d73a39d3d134f249
  6bd71bc59ead706df68649be4244b48d1f417bfc:
    version: 6bd71bc59ead706df68649be4244b48d1f417bfc
    blobstore_id: 0e39139b-28f0-4b3a-a2ce-b2856254c98c
    sha1: ab2983957772e09dcc0dd7024509fab89a479e6a
  8a75b00f03926ec6aa6dca2615a14011e6e99c57:
    version: 8a75b00f03926ec6aa6dca2615a14011e6e99c57
    blobstore_id: 4ea1a58b-f689-4134-b0fe-b7442a1682d8
    sha1: c8fc86ae4e8b330be8e2253be3ae7d4585c76623
  98abb897e51cfa15794bc2ca49089adda2e297b7:
    version: 98abb897e51cfa15794bc2ca49089adda2e297b7
    blobstore_id: 0fdbc13a-7ee0-4d55-8669-5a9a84c14ae5
    sha1: 000a2464e15909781afe670d1e368c70e395a895
  bb1b430f79cac6852bba567e6dce60354106ab65:
    version: bb1b430f79cac6852bba567e6dce60354106ab65
    blobstore_id: 9057bf8e-ce79-4095-65d5-dc331e421990
    sha1: 2ad87830069e2d3ffb2dfa8dcb2ac8830a4f08d4
  ccd97503e54ddb3e65eb0ddd25c7bc55e1297679:
    version: ccd97503e54ddb3e65eb0ddd25c7bc55e1297679
    blobstore_id: 6fedd49e-5e66-4a0e-a5cf-8ab6dc19e957
    sha1: 46146a01c3fff65d0913b218e930e15f94131903
  cdb793abffc9848ce88d2b71690d3d7d1bb1d8b0:
    version: cdb793abffc9848ce88d2b71690d3d7d1bb1d8b0
    blobstore_id: 62a78508-b010-409c-b040-a68ac95da693
    sha1: 14c588acab2c43ed09395598c90bf002ed5af8aa
  ce3b41a92f705388bf8ec6f397a5cf40955690b7:
    version: ce3b41a92f705388bf8ec6f397a5cf40955690b7
    blobstore_id: d1ac9a16-9306-4f24-5a5b-6b4a7b57add1
    sha1: 11ad6e5894ebed67a324bd69e7ec547acdb0c0c0
  d45a5dc2333fddae618804a28338f4849c1c5005:
    version: d45a5dc2333fddae618804a28338f4849c1c5005
    blobstore_id: cf024092-5aaa-4d07-9ce3-aef168512409
    sha1: 189038fc0cabb7cf75fa488b93d1aae618ea7d14
format-version: "2"
