- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/receivers/name=default/slack_configs?/-
  value:
    api_url: "((alertmanager_slack_api_url))"
    channel: "((alertmanager_slack_channel))"
    send_resolved: true
