# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: mysqld_exporter
    release: prometheus
    properties:
      mysqld_exporter:
        mysql:
          address: "((mysql_address))"
          username: "((mysql_username))"
          password: "((mysql_password))"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=mysql_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/mysql_alerts/*.alerts.yml

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=mysql_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=MySQL?/files/-
  value: /var/vcap/jobs/mysql_dashboards/*.json
