# Apply ./cf/add-prometheus-uaa-clients.yml to your cf-deployment based Cloud Foundry
# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: cf_exporter
    release: prometheus
    properties:
      cf_exporter:
        cf:
          api_url: https://api.((system_domain))
          client_id: cf_exporter
          client_secret: "((uaa_clients_cf_exporter_secret))"
          deployment_name: ((metron_deployment_name))
        metrics:
          environment: "((metrics_environment))"
        skip_ssl_verify: ((skip_ssl_verify))

- type: replace
  path: /instance_groups/-
  value:
    name: firehose
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: firehose_exporter
        release: prometheus
        consumes:
          reverse_log_proxy:
            deployment: cf
            from: reverse_log_proxy
        properties:
          firehose_exporter:
            doppler:
              subscription_id: "((metrics_environment))"
            logging:
              tls:
                ca: ((firehose_exporter_to_logs_provider.ca))
                cert: ((firehose_exporter_to_logs_provider.certificate))
                key: ((firehose_exporter_to_logs_provider.private_key))
            metrics:
              environment: "((metrics_environment))"
            skip_ssl_verify: ((skip_ssl_verify))

- type: replace
  path: /variables/-
  value:
    name: firehose_exporter_to_logs_provider
    options:
      ca: ((loggregator_ca_name)) # generally set it to /bosh-((name))/cf/loggregator_ca
      common_name: firehose-exporter
      extended_key_usage:
        - client_auth
        - server_auth
    type: certificate

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=cloudfoundry_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/cloudfoundry_alerts/*.alerts.yml

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=cloudfoundry_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=Cloudfoundry?/files/-
  value: /var/vcap/jobs/cloudfoundry_dashboards/cf*.json

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=Prometheus?/files/-
  value: /var/vcap/jobs/cloudfoundry_dashboards/prometheus*.json
