# Apply ./cf/add-prometheus-uaa-clients.yml to your cf-deployment based Cloud Foundry
# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: cf_exporter
    release: prometheus
    properties:
      cf_exporter:
        cf:
          api_url: https://api.((system_domain))
          client_id: cf_exporter
          client_secret: "((uaa_clients_cf_exporter_secret))"
          deployment_name: ((metron_deployment_name))
        metrics:
          environment: "((metrics_environment))"
        skip_ssl_verify: ((skip_ssl_verify))

- type: replace
  path: /instance_groups/-
  value:
    name: firehose
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: firehose_exporter
        release: prometheus
        properties:
          firehose_exporter:
            doppler:
              url: wss://doppler.((system_domain)):((traffic_controller_external_port))
              subscription_id: "((metrics_environment))"
              max_retry_count: 300
            uaa:
              url: https://uaa.((system_domain))
              client_id: firehose_exporter
              client_secret: "((uaa_clients_firehose_exporter_secret))"
            metrics:
              environment: "((metrics_environment))"
            skip_ssl_verify: ((skip_ssl_verify))

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=cloudfoundry_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/cloudfoundry_alerts/*.alerts

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=cloudfoundry_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_files/-
  value: /var/vcap/jobs/cloudfoundry_dashboards/*.json
