- type: remove
  path: /instance_groups/name=database

- type: remove
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/database

- type: remove
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/session
