# Bosh alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=bosh_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/bosh_alerts/*.alerts.yml

# Cloud Foundry alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=cloudfoundry_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/cloudfoundry_alerts/*.alerts.yml

# Concourse alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=concourse_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/concourse_alerts/*.alerts.yml

# Consul alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=consul_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/consul_alerts/*.alerts.yml

# Elasticsearch alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=elasticsearch_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/elasticsearch_alerts/*.alerts.yml

# HAProxy alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=haproxy_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/haproxy_alerts/*.alerts.yml

# Kubernetes alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=kubernetes_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/kubernetes_alerts/*.alerts.yml

# MySQL alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=mysql_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/mysql_alerts/*.alerts.yml

# RabbitMQ for PCF alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=p_rabbitmq_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/p_rabbitmq_alerts/*.alerts.yml

# Redis for PCF alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=p_redis_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/p_redis_alerts/*.alerts.yml

# PostgreSQL alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=postgres_alerts/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/postgres_alerts/*.alerts.yml

# Probe alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=probe_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/probe_alerts/*.alerts.yml

# Prometheus alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/prometheus_alerts/*.alerts.yml

# RabbitMQ alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=rabbitmq_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/rabbitmq_alerts/*.alerts.yml

# Redis Alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=redis_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/redis_alerts/*.alerts.yml

# Shield alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=shield_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/shield_alerts/*.alerts.yml
