builds:
  018636143a61f3961ba533e8ad879754ddab52e1:
    version: 018636143a61f3961ba533e8ad879754ddab52e1
    blobstore_id: 91925782-0ed8-469d-b6a5-9c14b35ce51b
    sha1: 72208eeb73a3cd0c48068c040ad119bf280f1954
  5e37763adfa2f4b948f7e7831ce7435b125b18d67764459a156b2e8f6b056cd9:
    version: 5e37763adfa2f4b948f7e7831ce7435b125b18d67764459a156b2e8f6b056cd9
    blobstore_id: 1df7b578-9ef4-4d37-630a-24c33dc42095
    sha1: sha256:60e16f7ce9f81954ef4846b70038355c9a8443901c5d814cb7b5dd1ffd0f93a0
  be2ac74b0c58cb93278fc44bb0a09cadd0250b24:
    version: be2ac74b0c58cb93278fc44bb0a09cadd0250b24
    blobstore_id: 3d0f9719-4fa1-4c09-92c8-3a88749bdac0
    sha1: b4a02a83c807f36aa6285df66858fcdcc02af3b0
  cb47482315785b06340bc86c7a92d153deaf740a:
    version: cb47482315785b06340bc86c7a92d153deaf740a
    blobstore_id: 8a9230e7-bfda-45f3-6230-424b85eba0e5
    sha1: c92cc54da279c270e47139d8e39c977019b4e61c
  d11721d9fc4a75c21b3e8a65a151d8e634955d86:
    version: d11721d9fc4a75c21b3e8a65a151d8e634955d86
    blobstore_id: fb91dc78-2b02-4508-7a43-591d7ded1386
    sha1: 27ba816095928a69878e2ee5a129aea26d4d2953
  ef74d5591e198a64b04946a0c3b642626186cac8:
    version: ef74d5591e198a64b04946a0c3b642626186cac8
    blobstore_id: aadbd70f-9c13-47ae-617c-29043e1ed130
    sha1: f343f14e743ea1bcc3407afb0ff233283c202b42
  f48d2bc8e39ca3c9494abe5694e9bdd366a09c2e0698ff8660cef8526d3b3e01:
    version: f48d2bc8e39ca3c9494abe5694e9bdd366a09c2e0698ff8660cef8526d3b3e01
    blobstore_id: 6aad80fe-7d28-4a19-4421-a28ea29b96c8
    sha1: sha256:96096c907b9edeace4213e2c40ba14f54b5cb1f3e9d14f8218aca98aec0a2aab
  f8c80c5b3681ca6a8fc600de094e3b17ca7ce022:
    version: f8c80c5b3681ca6a8fc600de094e3b17ca7ce022
    blobstore_id: d153259a-82cf-4079-a991-eb74b3bc129b
    sha1: c418f0b585d4097af47e2dcc379adea44c2e3611
format-version: "2"
