builds:
  0aea56e77276dfb3a2a1af8bf5995008cfa58dadc292dbe42bb264e66a3ca9c4:
    version: 0aea56e77276dfb3a2a1af8bf5995008cfa58dadc292dbe42bb264e66a3ca9c4
    blobstore_id: 346ee8ef-88a9-43b6-7ff1-ca0413d81474
    sha1: sha256:624fbcfeeae51251c4fdbd48eb5e0ba330fa091493c024e9a3930aec79c9a1ef
  115aaa183fc69bb462736e4dc98f15cca4c5b940:
    version: 115aaa183fc69bb462736e4dc98f15cca4c5b940
    blobstore_id: 3308f8f7-bcb5-4085-40f5-5b61f2da3633
    sha1: 724c577c8be3429d8054921c5023b41936d297b8
  15c5b21706c114d19fe94b66727a30116875069c:
    version: 15c5b21706c114d19fe94b66727a30116875069c
    blobstore_id: b8fbdc3c-016d-4ebe-6672-4eb935d10cf6
    sha1: b0fca9bdbcd1b9d0d5efe8a2b13927d68a1e49af
  25f0f1ad3da51f0e7376953fa5bb04c1989b29488fc995e0e22d052a200f74e3:
    version: 25f0f1ad3da51f0e7376953fa5bb04c1989b29488fc995e0e22d052a200f74e3
    blobstore_id: 9f261469-5da1-4781-725d-dee36c2564fc
    sha1: sha256:f4a58c64220d4b82ea0e123789bcf12988ed010a953b5a5501378dd17a22858e
  277cc87b6f934f70d244b9f8dd6be59042142af7:
    version: 277cc87b6f934f70d244b9f8dd6be59042142af7
    blobstore_id: 8cf0a30e-21b6-4184-58b3-84571e9c3e13
    sha1: e669ad33acddcfda6347edc92e8855382f130442
  3cc33199b420f0f7aa8b37d4d1a335a58d299904:
    version: 3cc33199b420f0f7aa8b37d4d1a335a58d299904
    blobstore_id: 498c5b77-0934-4a3c-6bc9-67e1b9bef6a9
    sha1: 27a59c02fa33aef3e92fc56d86d7d2d7da6d730d
  41d0b2b53c434c7f6552277222c558e372ca418b:
    version: 41d0b2b53c434c7f6552277222c558e372ca418b
    blobstore_id: 716eee32-4543-42ed-795f-99e968924a95
    sha1: bb7a202bd461e9d5f290abf7f69036d29e93cfc6
  7f468db7b4c5a3ea2a76754880406576d9c48681:
    version: 7f468db7b4c5a3ea2a76754880406576d9c48681
    blobstore_id: d0114669-47a2-40ef-6841-cada9f1a5ed5
    sha1: 2ca381e097079c11c25073b5e1448d76e422daae
  8d8f02d7a00cc79ee7920cbf6fe266b64dbfac6b:
    version: 8d8f02d7a00cc79ee7920cbf6fe266b64dbfac6b
    blobstore_id: 4c5fa661-f4cc-443c-42aa-f9ad4e91e35c
    sha1: 079c3f070087e00fd9727d8e01ae072d33b9bff1
  a964acc9f8a7b0c23d0034be4f93283b1b7fadfc:
    version: a964acc9f8a7b0c23d0034be4f93283b1b7fadfc
    blobstore_id: 4fac5176-5f19-48d9-5c4d-589666cb1b73
    sha1: 128c0dae1b6b0ec676b4df77b292a6264ac4504c
  ba673e3798ff386f63174c72bcf098d1a542bd4c:
    version: ba673e3798ff386f63174c72bcf098d1a542bd4c
    blobstore_id: 01bb7580-1042-4cae-4110-2762346ca645
    sha1: b36cebac2bfed32580a5ae6118088dca46d2ee62
  c4813a81193354cf53a632aba52b782419aac83e34e3dfc678c912fc5b288543:
    version: c4813a81193354cf53a632aba52b782419aac83e34e3dfc678c912fc5b288543
    blobstore_id: fb23adce-8582-465f-7b07-8351bd67d396
    sha1: sha256:a6ccb182c85b8ed1dfa97cc895071963a0e1b6a211ca96b67e4e91feabef5781
  cc4982f10c6e7f15a23a9437f09bce511450909f:
    version: cc4982f10c6e7f15a23a9437f09bce511450909f
    blobstore_id: f2d707b7-be84-41de-6696-ea7ca61bfb5d
    sha1: b7dc9261d262ac7dbf2db72533b2c07129b08b99
  fbdb4c67898a90aa1df93f1e914a607f597eb765948004eb968bf8e70a51dd05:
    version: fbdb4c67898a90aa1df93f1e914a607f597eb765948004eb968bf8e70a51dd05
    blobstore_id: 15e42493-0fec-4bd8-46f5-f2225de1937c
    sha1: sha256:0b4dd28e1728604271152ce334c0ccc73383ca6d05928b75fdae8df70e727e5f
format-version: "2"
