alertmanager/alertmanager-0.29.0.linux-amd64.tar.gz:
  size: 33963485
  object_id: 93f33396-fea8-4931-5403-799446783497
  sha: sha256:3b12d6dac67eef1cfbe42c6153f156e7b968e6f04298b4d966d51ba5e271a1b3
blackbox_exporter/blackbox_exporter-0.28.0.linux-amd64.tar.gz:
  size: 16148437
  object_id: fffb1519-49b5-4d7d-44cb-2ecc03168524
  sha: sha256:caf5d242fb1cf6d5cb678f3f799f22703d4fafea26b03dcbbd7e1f1825e06329
bosh_exporter/bosh_exporter-3.7.2.linux-amd64.tar.gz:
  size: 5040163
  object_id: 5f194124-5c2f-4e79-4114-f9f92bc81991
  sha: sha256:8d0ee6dcb0466ee22751b140a5f73ebc3a186c68bb4d3a6c007d164c237b26aa
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-v0.54.1-linux-amd64:
  size: 39583731
  object_id: 3ed7b898-8b86-434c-7fb6-804bc3463f53
  sha: sha256:21be8d2797433048474e676d37c215c28fb171509448ef9b1c4648a564e39595
cf_exporter/cf_exporter_2.0.1.linux-amd64.tar.gz:
  size: 8689747
  object_id: 0b03a38b-a47d-4eb1-59b7-8390a10f8356
  sha: sha256:4b1451dafb4bb13a06a6353022402ad5f824bb6872a095247b7951537a4b7371
collectd_exporter/collectd_exporter-0.7.0.linux-amd64.tar.gz:
  size: 8865082
  object_id: d3c9e176-b121-4910-6db5-1e7017eacd82
  sha: sha256:a0410b74d7250e2f6dac2d0ca7d74ccac7813c2ceb04586e9fb262e0cd822364
consul_exporter/consul_exporter-0.13.0.linux-amd64.tar.gz:
  size: 10054358
  object_id: d4eacf74-84eb-4282-4150-b22d7d9aba7b
  sha: sha256:2a8da4147330c6e19c9665deca1c419d507e100de6c8b7c58c0715ff25453773
credhub_exporter/credhub_exporter_0.69.3_linux_amd64.tar.gz:
  size: 4811384
  object_id: 86906b26-6f64-4c6d-77f7-d510ceb22394
  sha: sha256:4d0f9b14838cc84a6a57f0519e4388683c8549df78aca92ed979d774eed6e962
elasticsearch_exporter/elasticsearch_exporter-1.9.0.linux-amd64.tar.gz:
  size: 5656427
  object_id: df2882b7-2ed7-4d4f-73ae-8b899663255a
  sha: sha256:472fcafab63c5a3a2dd17d9a5e9919de4741a72e4f286c1e6252f3d99cebe425
firehose_exporter/firehose_exporter-6.2.0.linux-amd64.tar.gz:
  size: 9102454
  object_id: 065e08b0-0023-46ba-4955-ee5daf5e40f0
  sha: sha256:6f81a643a158a578c7e8b08e3fc06044ba957806d87c33d58955c1142cd54d8f
firehose_exporter/firehose_exporter_7.1.11.linux-amd64.tar.gz:
  size: 5313124
  object_id: 557ef3ad-97e6-4649-5651-5f39aa8979c9
  sha: sha256:7f1ce08cd9bcaaca81c0598fd96e2c9d577a8a5cef18836dbb395b5edd2604e5
fontconfig/fontconfig-2.17.1.tar.xz:
  size: 1326312
  object_id: 218869a6-f4fd-4190-5517-160c8084f27a
  sha: sha256:9f5cae93f4fffc1fbc05ae99cdfc708cd60dfd6612ffc0512827025c026fa541
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.14.1.tar.gz:
  size: 4135293
  object_id: 9db73bd0-b9b8-41a3-7b6b-0ac2e8b89832
  sha: sha256:174d9e53402e1bf9ec7277e22ec199ba3e55a6be2c0740cb18c0ee9850fc8c34
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-10.4.19.linux-amd64.tar.gz:
  size: 120000970
  object_id: 9160680f-c4fd-40ac-7748-4d0c05f1947a
  sha: sha256:110006a65a90195bcb7fe5a8b53ca152a26b6179454a5fd137be093c24244ef8
grafana/grafana-11.6.6.linux-amd64.tar.gz:
  size: 182981353
  object_id: f78b8b11-32b3-483b-59a5-241646822430
  sha: sha256:8a57ac91eb470b0949f30aa528a77955c04009d5b307e124550a05678dcade56
grafana_plugins/flant-statusmap-panel-0.5.1.zip:
  size: 289519
  object_id: 1c011a4e-29fb-4081-4c58-947735d9bb9f
  sha: sha256:6841f3687f70711673766646aca3a2bb2d28a8e2e6336370329c90d917beb5a9
grafana_plugins/grafana-clock-panel-2.1.8.zip:
  size: 485744
  object_id: d3957514-6a52-4270-5a48-f4474fba4ae9
  sha: sha256:c4a87a52e48ae169e4d19136e4a8044516958c02840de6605d85ffa42828c062
grafana_plugins/grafana-worldmap-panel-v1.0.6.zip:
  size: 1089481
  object_id: b385e208-fa32-4f0b-5131-c4301d79c230
  sha: sha256:9321d77b64d29404a1c9e62bfc136a71f8db17f5cf65827e972c94fbe619f94d
grafana_plugins/jdbranham-diagram-panel-1.10.4.zip:
  size: 6446989
  object_id: 71658584-b01e-42ee-7b16-5bd775ff5ce4
  sha: sha256:f95b691d0a73da8910145d958bc6e59ed66b47a26cf7cf07bb41f057ff2a5a66
grafana_plugins/mtanda-histogram-panel-v0.1.6.zip:
  size: 76062
  object_id: 52255f76-001d-4401-514b-d1ce42b82eb3
  sha: sha256:60495c5eca135fdc31530f299e2caab3389840ad8526e17a0c6e0d5934e6858b
grafana_plugins/vonage-status-panel-v1.0.10.zip:
  size: 401708
  object_id: 1d94c564-ce22-461d-6689-3d2a728fdc55
  sha: sha256:1d3ffa533def063f077415cb775bbd54ad4bd1b9f5bfe7e62250635b77dc5589
graphite_exporter/graphite_exporter-0.16.0.linux-amd64.tar.gz:
  size: 22242517
  object_id: 40283104-d085-4004-69a1-75c2b0c9c03d
  sha: sha256:129acf14bb62dc32596ff8aed40a526a66260b2736801bc546be407436dd32d8
influxdb_exporter/influxdb_exporter-0.12.0.linux-amd64.tar.gz:
  size: 7852845
  object_id: 56c13032-b2a4-4d6d-611b-ef64ecdcaa72
  sha: sha256:1b00556c5aebcf70654ef96a0e0fe301dd7867a1864004986188d966a27f4fa1
ingestor_exporter/ingestor_exporter-2.2.0.linux-amd64.tar.gz:
  size: 5924704
  object_id: a0ce369b-0024-4b67-75ea-2bb51551d9b7
  sha: sha256:54be2bbc9f89ffbf8f70c476ec2b1835cbd619db94d18d1ae537c1a602e9b116
jq/jq-1.8.1.linux64:
  size: 2255816
  object_id: ee005254-84ac-4c62-4e4b-4f26b20022c4
  sha: sha256:020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d
kafka_exporter/kafka_exporter-1.9.0.linux-amd64.tar.gz:
  size: 12733803
  object_id: b72cc82a-ec34-43fc-5b4b-642d7b927bc5
  sha: sha256:c722518ad71c53b3988ea26ae2bd387bb596ce7a98fc639d08bf639a537699a1
libxml2/libxml2-2.15.0.tar.xz:
  size: 2004476
  object_id: be9065c9-f6b6-4a5f-7b22-5dc7ad1086d5
  sha: sha256:5abc766497c5b1d6d99231f662e30c99402a90d03b06c67b62d6c1179dedd561
logstash_exporter/prometheus-logstash-exporter-0.7.15.linux-amd64.tar.gz:
  size: 7051883
  object_id: e55bb8b0-e8f0-4b86-7333-57c1cc3bd78f
  sha: sha256:ebcdbf2155d6be9ddc8a060fc6ce2b0d6e9df177604909c5f6549055306cfc6e
memcached_exporter/memcached_exporter-0.15.3.linux-amd64.tar.gz:
  size: 9283253
  object_id: ccf1389c-1d81-4c1d-617f-7549865c9bfb
  sha: sha256:7e4eb9f4af3971918fbfd35fa31b74dc08b2a728f488f934d8c7c7ecced2c85f
mongodb_exporter/mongodb_exporter-0.47.1.linux-amd64.tar.gz:
  size: 11705129
  object_id: c0e4151e-d7a3-4efc-5060-3b0680060575
  sha: sha256:5cdbd851a3a7236baaa4de23f2acecd37b4e849d3985eaff5785014c54b26635
mysqld_exporter/mysqld_exporter-0.18.0.linux-amd64.tar.gz:
  size: 9634286
  object_id: e91e8898-8c87-4649-494a-9a21f051bfa8
  sha: sha256:46e8f45654352bdd42d162b2b4a68f00055d45acc168f9c068235b9e3acc39c1
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.29.1.tar.gz:
  size: 1285529
  object_id: 51f96b71-b2aa-4c35-69f3-ee3afe56e622
  sha: sha256:c589f7e7ed801ddbd904afbf3de26ae24eb0cce27c7717a2e94df7fb12d6ad27
nginx/pcre-8.45.tar.gz:
  size: 2096552
  object_id: 07d80377-8e45-4f83-7d5b-47c2df280efb
  sha: sha256:4e6ce03e0336e8b4a3d6c2b70b1c5e18590a5673a98186da90d4f33c23defc09
postgres_exporter/postgres_exporter-0.18.1.linux-amd64.tar.gz:
  size: 10322165
  object_id: f76c5796-ce99-4d7f-631f-577238d179c3
  sha: sha256:1630965540d49a4907ad181cef5696306d7a481f87f43978538997e85d357272
prometheus/prometheus-2.55.1.linux-amd64.tar.gz:
  size: 111626041
  object_id: 8928b817-2862-48ec-54ac-970c7a835bd2
  sha: sha256:19700bdd42ec31ee162e4079ebda4cd0a44432df4daa637141bdbea4b1cd8927
prometheus/prometheus-3.6.0.linux-amd64.tar.gz:
  size: 121206080
  object_id: 2dab0f3a-5264-4ada-442d-ed95f3b186c0
  sha: sha256:2002ef4a55a64161affccd2786c7081d4e3b3a8d08786a98b3bb110971414916
pushgateway/pushgateway-1.11.1.linux-amd64.tar.gz:
  size: 11854015
  object_id: 8df06d0e-73a9-4125-60b6-903bf9c5b7d2
  sha: sha256:6ce6ffab84d0d71195036326640295c02165462abd12b8092b0fa93188f5ee37
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.77.0.linux-amd64.tar.gz:
  size: 3888474
  object_id: e9689759-b3ab-47a5-5124-bdfa51d78fb7
  sha: sha256:e068d2f081b959b59b3fc25cdfc3477ec10766301ecfbea64a661b443f718c53
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.18.0.linux-amd64.tar.gz:
  size: 12333657
  object_id: 8a002887-36ec-4559-4471-f4e72d8e69dd
  sha: sha256:7c51f42b03a88c73572a6b225ac3776814f48eb2c89d5d46315c92810557bbeb
statsd_exporter/statsd_exporter-0.28.0.linux-amd64.tar.gz:
  size: 9097691
  object_id: d79da327-a1dd-4016-7563-b3e3abb4929f
  sha: sha256:6951081e3115669e4353975f897dda1cefddef5a5d16addc908485d9be16b72b
util-linux/util-linux-2.41.2.tar.xz:
  size: 9612488
  object_id: 0019cab1-3acc-4243-6546-196653518cce
  sha: sha256:6062a1d89b571a61932e6fc0211f36060c4183568b81ee866cf363bce9f6583e
vault_exporter/vault_exporter_0.1.3_linux_amd64.tar.gz:
  size: 3773592
  object_id: 75bd13c6-4452-447a-6847-9f82599ef36d
  sha: sha256:26d0f36233270bb0ede98da94c2cdad09180cbadd7ee4ae3205961d13e9b7c55
