alertmanager/alertmanager-0.20.0.linux-amd64.tar.gz:
  size: 23928771
  object_id: 4e225dc5-728a-4579-4f30-64b15e04a5f8
  sha: sha256:3a826321ee90a5071abf7ba199ac86f77887b7a4daa8761400310b4191ab2819
blackbox_exporter/blackbox_exporter-0.16.0.linux-amd64.tar.gz:
  size: 8314959
  object_id: 3f5da843-9e34-4a76-448c-d2d91779eeed
  sha: sha256:52d3444a518ea01f220e08eaa53eb717ef54da6724760c925ab41285d0d5a7bd
bosh_exporter/bosh_exporter-3.3.0.linux-amd64.tar.gz:
  size: 7951925
  object_id: 1cb948b8-aa67-4af5-75f0-bfdf6fb2dc8f
  sha: sha256:7a998ab28b8c4b2ba075f72a580d608a346478fe9b64725ea767997bd7a6f916
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-0.34.0.tar.gz:
  size: 15136329
  object_id: 4a7b89f8-1749-4616-7c98-d1c949db587b
  sha: sha256:2ae8791a5f7f079a94defb0376701698054188c6df4d6f67a63c6db26cdd3180
cf_exporter/cf_exporter-0.10.0.linux-amd64.tar.gz:
  size: 7127668
  object_id: b283e6e7-0df3-48d6-663c-ace280fbea64
  sha: sha256:d5ac3d8ecc76d4f0c28e0ab3f5422357227ad56aae9801aa19316390d62df001
collectd_exporter/collectd_exporter-0.4.0.linux-amd64.tar.gz:
  size: 3340495
  object_id: 428779f0-9ae9-4a9b-6a53-9207c416cf14
  sha: 56c122cb29777e77f7db008b5e6bd49de35060b0
consul_exporter/consul_exporter-0.6.0.linux-amd64.tar.gz:
  size: 7227104
  object_id: 5cbe0ed9-6651-4b97-7992-c84080ef806d
  sha: sha256:70770e54cfdd0997f3031357ce0f45bbe16e7d1b44fc3a0771b192c5bfe1af10
credhub_exporter/credhub_exporter-0.1.6.linux-amd64.tar.gz:
  size: 6227648
  object_id: 0ae6c921-30ff-457e-40a2-fa04a14886f9
  sha: 1fe502186faa6c85be1ae3a3d55aec5cab247867
elasticsearch_exporter/elasticsearch_exporter-1.1.0.linux-amd64.tar.gz:
  size: 3632462
  object_id: 985f1a9f-9883-48c0-6f05-8e739db410a5
  sha: sha256:1d2444d7cbf321cb31d58d2fecc08c8bc90bbcec581f8a1ddb987f9ef425482b
firehose_exporter/firehose_exporter-6.1.0.linux-amd64.tar.gz:
  size: 9092157
  object_id: 879c7a3f-3fc0-4180-563b-52ae1511a3af
  sha: sha256:4e02b9998c72b7fe3d69a3db474bb6feb544f95751653f4b6a1fced3fb4144f2
fontconfig/fontconfig-2.13.92.tar.gz:
  size: 2127384
  object_id: 2ff7a520-f3dd-487f-6af0-e7a7a8f758f3
  sha: sha256:3406a05b83a42231e3df68d02bc0a0cf47b3f2e8f11c8ede62267daf5f130016
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.9.1.tar.gz:
  size: 2533956
  object_id: d74e6686-1bf9-46d4-7115-1b15aa2ca41c
  sha: 7498739e34e5dca4c61d05efdde6191ba69a2df0
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-6.5.3.linux-amd64.tar.gz:
  size: 61041681
  object_id: fed4f46c-bbd4-44b7-598e-f0b76008a570
  sha: sha256:02fe78f1d6842e043ca61a64272dd7dfdb4103486f163501b08a923f0f0452be
graphite_exporter/graphite_exporter-0.6.2.linux-amd64.tar.gz:
  size: 6918576
  object_id: 823ea501-25c1-404a-5e66-7d131c9308b0
  sha: sha256:9b962bd06406ece4a865ad6947a6e652e48a92a0d77e496a0351c04e9c2c5e9e
haproxy_exporter/haproxy_exporter-0.10.0.linux-amd64.tar.gz:
  size: 5975717
  object_id: 7e2d5da9-a10d-4601-67dc-995b803a97b2
  sha: 7f47a9205e84f6ca115e67cea953975c3d9c4a1e
influxdb_exporter/influxdb_exporter-0.3.0.linux-amd64.tar.gz:
  size: 6327430
  object_id: 9d9205f4-3d01-4e57-4fb9-30461b2be62f
  sha: sha256:0267cad0f40a961960679b711f28f839950dc55ac0c05fd11a475d2289abc618
ingestor_exporter/ingestor_exporter-2.2.0.linux-amd64.tar.gz:
  size: 5924704
  object_id: a0ce369b-0024-4b67-75ea-2bb51551d9b7
  sha: sha256:54be2bbc9f89ffbf8f70c476ec2b1835cbd619db94d18d1ae537c1a602e9b116
jq/jq-1.6.linux64:
  size: 3953824
  object_id: 04453e77-c1dd-40ad-49a8-54dedf95d8bf
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libxml2/libxml2-2.9.9.tar.gz:
  size: 5476717
  object_id: c8cecac6-6d78-4753-70a4-05dbcc3f19ae
  sha: sha256:94fb70890143e3c6549f265cee93ec064c80a84c42ad0f23e85ee1fd6540a871
memcached_exporter/memcached_exporter-0.6.0.linux-amd64.tar.gz:
  size: 6531705
  object_id: c064ec3e-0342-46c4-6ca2-ed31a01c8bae
  sha: sha256:20382d37ca99bbde2661fdbfb43a181f95d68889b761e56b39678e31bb23b64c
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.12.1.linux-amd64.tar.gz:
  size: 7121565
  object_id: 3e8d5841-8c2e-44af-40cd-efa31f3473cc
  sha: sha256:133b0c281e5c6f8a34076b69ade64ab6cac7298507d35b96808234c4aa26b351
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.16.1.tar.gz:
  size: 1032630
  object_id: 260514ec-ee20-467d-485f-c86e103a7d75
  sha: sha256:f11c2a6dd1d3515736f0324857957db2de98be862461b5a542a3ac6188dbe32b
nginx/pcre-8.43.tar.gz:
  size: 2085854
  object_id: 3653d041-229c-42ca-6df0-4e2485393c1b
  sha: sha256:0b8e7465dc5e98c757cc3650a20a7843ee4c3edf50aaf60bb33fd879690d2c73
postgres_exporter/postgres_exporter_v0.8.0_linux-amd64.tar.gz:
  size: 6016522
  object_id: 5c554234-7e77-43a3-51fd-1c1032cb710a
  sha: sha256:272ed14d3c360579d6e231db34a568ec08f61d2e163cf111e713929ffb6db3f5
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.15.2.linux-amd64.tar.gz:
  size: 59204993
  object_id: 309fe02a-4190-4bac-454b-9a7e77d9dd73
  sha: sha256:579f800ec3ec2dc9a36d2d513e7800552cf6b0898f87a8abafd54e73b53f8ad0
pushgateway/pushgateway-1.0.1.linux-amd64.tar.gz:
  size: 8970480
  object_id: 845c386a-116f-47e3-53e6-43f822f96953
  sha: sha256:b81b45bd1c9de86cf17531932b414cc65051102eb82d3e6bc5cef16ed703ce83
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.3.5.linux-amd64.tar.gz:
  size: 3376514
  object_id: a857c09b-659d-4a3f-72f6-66473ac51a33
  sha: sha256:bb408128cb4c3024c8532dae3539080349687cc96cbab51a1e06e9a15519b874
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.6.0.linux-amd64.tar.gz:
  size: 5755060
  object_id: fa8a4c12-567d-4e94-530a-24a756879a34
  sha: e4adf3ca00920d705dcfe369d50272ba3f9bf1c5
statsd_exporter/statsd_exporter-0.14.1.linux-amd64.tar.gz:
  size: 7189058
  object_id: 1389f3e3-acf7-49f7-4369-caa35a600854
  sha: sha256:c9e685db2558b96d40bb60c36420054457421fce8c6aad4b7fa14d9cff0ff04d
util-linux/util-linux-2.35.tar.gz:
  size: 10981874
  object_id: 45c00f38-de20-428a-5e83-706035c7194d
  sha: sha256:98acab129a8490265052e6c1e033ca96d68758a13bb7fcd232c06bf16cc96238
vault_exporter/vault_exporter_0.1.2_linux_amd64.tar.gz:
  size: 3809657
  object_id: b57907a1-69f8-4e62-6708-e0e632b8ec32
  sha: 4c6e2770de08eedf96b33e9fde508d60c07aafe8
