alertmanager/alertmanager-0.25.0.linux-amd64.tar.gz:
  size: 29254678
  object_id: 4494fc1b-79f6-4a31-70ee-f0e6818fd749
  sha: sha256:206cf787c01921574ca171220bb9b48b043c3ad6e744017030fed586eb48e04b
blackbox_exporter/blackbox_exporter-0.23.0.linux-amd64.tar.gz:
  size: 10831812
  object_id: 8e7cd3ed-33bb-482c-411e-91f4b36745e1
  sha: sha256:63bd4fde6984db79c95e1502a0ab47da6194d763bff22a04d1f50c4fd8322b84
bosh_exporter/bosh_exporter-3.4.0.linux-amd64.tar.gz:
  size: 7727120
  object_id: df3639b9-15d4-4856-6ae1-35dfefac87c9
  sha: sha256:3d9cd96367d35cf4258c90f637f9778711b1c252c00661bd30d5e60ee3e38478
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-v0.47.0-linux-amd64:
  size: 44642706
  object_id: 92e9dea2-22f4-4284-510a-a5697dc25328
  sha: sha256:caf4491298e0702f9d0c6a1d1949767f5c6400f77e12cd3524d6d3fcc66abc2a
cf_exporter/cf_exporter_1.1.0.linux-amd64.tar.gz:
  size: 6988459
  object_id: 53b851b8-6ab8-46b2-7356-2b26e6a846bd
  sha: sha256:bfc66e44c92eae21271fb466c37df77a5f2bff32508f2af0f169c6192d66dceb
collectd_exporter/collectd_exporter-0.5.0.linux-amd64.tar.gz:
  size: 7253249
  object_id: 6584fd01-47ea-4cd2-75de-cf191caaa33f
  sha: sha256:5b906b1ea49c119024350c10b4b8491857a20336a0ffd778a3f10d7536a6d123
consul_exporter/consul_exporter-0.9.0.linux-amd64.tar.gz:
  size: 8799847
  object_id: ae47c543-ad44-499a-6478-d976c4d1aae5
  sha: sha256:918bbbfaec650a9a1159edc663c7b09d6477cd96c078edef6d9fe608ece3c4ff
credhub_exporter/credhub_exporter_0.23.0_linux_amd64.tar.gz:
  size: 4167854
  object_id: 83c6777b-e1ad-4392-4ce8-a3a921b3ede7
  sha: sha256:188ff6f20e81015dc60432d188dee2c6bf3368ff1742919a2c8ecc7f37658f2a
elasticsearch_exporter/elasticsearch_exporter-1.5.0.linux-amd64.tar.gz:
  size: 4394851
  object_id: b502c37b-fed4-4c80-7d34-77ff079e8c66
  sha: sha256:66dfe9981e860c9f068f04fb82659da1ddcf9a4581d579f79d9febf431b05ac7
firehose_exporter/firehose_exporter-6.2.0.linux-amd64.tar.gz:
  size: 9102454
  object_id: 065e08b0-0023-46ba-4955-ee5daf5e40f0
  sha: sha256:6f81a643a158a578c7e8b08e3fc06044ba957806d87c33d58955c1142cd54d8f
firehose_exporter/firehose_exporter_7.0.0.linux-amd64.tar.gz:
  size: 4651429
  object_id: bafeaea4-1752-45b4-59c3-5b2a746b1738
  sha: sha256:16f5744d37693e08216ac902e72948fef9c3612489583764e5c3e40f00c25321
fontconfig/fontconfig-2.14.2.tar.xz:
  size: 1440844
  object_id: 7656fb30-b5c6-45ac-4d2c-48ccdca1cfbd
  sha: sha256:dba695b57bce15023d2ceedef82062c2b925e51f5d4cc4aef736cf13f60a468b
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.9.1.tar.gz:
  size: 2533956
  object_id: d74e6686-1bf9-46d4-7115-1b15aa2ca41c
  sha: 7498739e34e5dca4c61d05efdde6191ba69a2df0
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-9.5.1.linux-amd64.tar.gz:
  size: 78487778
  object_id: f847c659-596f-49cc-57cd-bafd3464bcc3
  sha: sha256:d9b7505cdd4299c1835c36547ffe2e62d3b0ec7600dca2c644a0519572c9c387
grafana_plugins/flant-statusmap-panel-0.5.1.zip:
  size: 289519
  object_id: 1c011a4e-29fb-4081-4c58-947735d9bb9f
  sha: sha256:6841f3687f70711673766646aca3a2bb2d28a8e2e6336370329c90d917beb5a9
grafana_plugins/grafana-clock-panel-2.1.3.zip:
  size: 476818
  object_id: d1fb0e6d-3cec-4135-4ff1-025d820dcdf6
  sha: sha256:4f9585399630bf8da4262f1553a16387136c4044273a7448b2eaa743466bb681
grafana_plugins/grafana-worldmap-panel-v0.3.2.zip:
  size: 2681129
  object_id: 48b520b3-8b0a-4b7c-46dd-cd5656914928
  sha: sha256:306009cd2f57f75c7ac2ddf4e631f57212e85b7cddee92180f04673e0f6aae01
grafana_plugins/jdbranham-diagram-panel-1.7.3.zip:
  size: 3749121
  object_id: 63689dcf-b8fe-46b4-6dc9-d4d3ee052678
  sha: sha256:e79848168bdf4ac542088943fed756072fa5af25e8c7ba2b6d08de6de015a268
grafana_plugins/mtanda-histogram-panel-v0.1.6.zip:
  size: 76062
  object_id: 52255f76-001d-4401-514b-d1ce42b82eb3
  sha: sha256:60495c5eca135fdc31530f299e2caab3389840ad8526e17a0c6e0d5934e6858b
grafana_plugins/vonage-status-panel-v1.0.10.zip:
  size: 401708
  object_id: 1d94c564-ce22-461d-6689-3d2a728fdc55
  sha: sha256:1d3ffa533def063f077415cb775bbd54ad4bd1b9f5bfe7e62250635b77dc5589
graphite_exporter/graphite_exporter-0.13.3.linux-amd64.tar.gz:
  size: 14688607
  object_id: 8758f3ad-1784-467d-616f-f899142a4e88
  sha: sha256:8a34de40dedb5c03259b55e16f1a3e282c1f20f0da1103c444b358ebb4d03d92
haproxy_exporter/haproxy_exporter-0.15.0.linux-amd64.tar.gz:
  size: 8197764
  object_id: 3c1ec2f4-e971-4012-627b-f0ba993b35c5
  sha: sha256:ac200872b734e2f9c0211997f7f9c0ca5ad6522996c37aed39a732d5f3c0de16
influxdb_exporter/influxdb_exporter-0.11.3.linux-amd64.tar.gz:
  size: 7035862
  object_id: 19d0b75c-a19d-4bf4-7b53-8d80e1e9d9e5
  sha: sha256:52c3faaf0f7fc9fe38e3d7a6d1ab1ab2c4da55ae512360ebe9f1bde190c55789
ingestor_exporter/ingestor_exporter-2.2.0.linux-amd64.tar.gz:
  size: 5924704
  object_id: a0ce369b-0024-4b67-75ea-2bb51551d9b7
  sha: sha256:54be2bbc9f89ffbf8f70c476ec2b1835cbd619db94d18d1ae537c1a602e9b116
jq/jq-1.6.linux64:
  size: 3953824
  object_id: 04453e77-c1dd-40ad-49a8-54dedf95d8bf
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libxml2/libxml2-2.11.0.tar.xz:
  size: 2617968
  object_id: 0a3bc78d-7958-4c64-613d-d9d376cde373
  sha: sha256:b1a2fca3f7722d6c35a4f24974a1b5800e4d84ec5cb756bc61ef2b8c75a19e36
memcached_exporter/memcached_exporter-0.11.3.linux-amd64.tar.gz:
  size: 7746561
  object_id: ba6f2dbe-24a9-4260-769a-33bfff8d558b
  sha: sha256:39bc1f325ac973e927057138742182fa2536a7ee549a608c0c43b5fbb9ed5711
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.14.0.linux-amd64.tar.gz:
  size: 7450991
  object_id: 1daa0fd1-e981-49e5-5cc6-37ccd04602d6
  sha: sha256:c17402137a4e9745f593127f162c1003298910cb8aa7d05bee3384738de094ae
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.24.0.tar.gz:
  size: 1112471
  object_id: e7229568-cbb0-47ad-70ff-712c001a47ca
  sha: sha256:77a2541637b92a621e3ee76776c8b7b40cf6d707e69ba53a940283e30ff2f55d
nginx/pcre-8.45.tar.gz:
  size: 2096552
  object_id: 07d80377-8e45-4f83-7d5b-47c2df280efb
  sha: sha256:4e6ce03e0336e8b4a3d6c2b70b1c5e18590a5673a98186da90d4f33c23defc09
postgres_exporter/postgres_exporter-0.12.0.linux-amd64.tar.gz:
  size: 8513358
  object_id: 53d53d8e-d553-4dde-5eec-ee5343a51c88
  sha: sha256:e3301d4b8b666b870491f520c098cc4c1ce32bb5dc22ee7f40ec1914d27be891
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.43.0.linux-amd64.tar.gz:
  size: 91091544
  object_id: e832a5fa-90eb-451e-77dd-6b8b37d1c6c7
  sha: sha256:cfea92d07dfd9a9536d91dff6366d897f752b1068b9540b3e2669b0281bb8ebf
pushgateway/pushgateway-1.5.1.linux-amd64.tar.gz:
  size: 10051993
  object_id: 34807b91-69fb-45fb-4469-bee3240f2cf6
  sha: sha256:3c1fb80e0e777fb98a9171c888adf9553bfab5a0b58af730ae108ac0970ec2a4
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.50.0.linux-amd64.tar.gz:
  size: 3573462
  object_id: 69d31ed4-5738-4407-7072-08da907d4f11
  sha: sha256:f634cf833ce563a38ae15fbf9d5222d671e89a0a56a8f081419aebdc0f8d0d21
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.14.1.linux-amd64.tar.gz:
  size: 10741899
  object_id: c92a8f07-ad47-46b2-7362-51820927430a
  sha: sha256:5967cbcec8de9ad29088b3ec67f141b17ea7c098186a4f563c78a2de73876c2d
statsd_exporter/statsd_exporter-0.24.0.linux-amd64.tar.gz:
  size: 7898529
  object_id: 3d29a800-d0a6-4c7d-46a3-778d44f114fc
  sha: sha256:49c84b454dc6ff8f828ff0b9615e8e09455db679e6d1193546a9610a207c3e35
util-linux/util-linux-2.38.1.tar.xz:
  size: 7495904
  object_id: 5cf63a34-123f-422f-5a62-0e2b64254471
  sha: sha256:60492a19b44e6cf9a3ddff68325b333b8b52b6c59ce3ebd6a0ecaa4c5117e84f
vault_exporter/vault_exporter_0.1.3_linux_amd64.tar.gz:
  size: 3773592
  object_id: 75bd13c6-4452-447a-6847-9f82599ef36d
  sha: sha256:26d0f36233270bb0ede98da94c2cdad09180cbadd7ee4ae3205961d13e9b7c55
