alertmanager/alertmanager-0.23.0.linux-amd64.tar.gz:
  size: 25115445
  object_id: 0f343151-dbd9-450a-4c97-57e5523900bb
  sha: sha256:77793c4d9bb92be98f7525f8bc50cb8adb8c5de2e944d5500e90ab13918771fc
blackbox_exporter/blackbox_exporter-0.19.0.linux-amd64.tar.gz:
  size: 8881739
  object_id: 50469191-5d8a-46bc-5443-2dc31f6b7040
  sha: sha256:af2ae1394c4f9b46962ac1510e1dacac78115c11e625991fb6c54825d2240896
bosh_exporter/bosh_exporter-3.3.0.linux-amd64.tar.gz:
  size: 7951925
  object_id: 1cb948b8-aa67-4af5-75f0-bfdf6fb2dc8f
  sha: sha256:7a998ab28b8c4b2ba075f72a580d608a346478fe9b64725ea767997bd7a6f916
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-0.37.0.tar.gz:
  size: 16905721
  object_id: 9d353079-a632-4033-4c98-eda68a05eb93
  sha: sha256:07e2f631fb99d058d7d783d457fdb3039c4dbd49a87b2be64143849031b89fe2
cf_exporter/cf_exporter-0.10.1.linux-amd64.tar.gz:
  size: 7345936
  object_id: d6639464-cc47-4a19-6e24-8533e8094184
  sha: sha256:f161c1410e40e2912b55aa80d252fd08fb839282c1f20a9a4f0a812ff7cc5a43
collectd_exporter/collectd_exporter-0.5.0.linux-amd64.tar.gz:
  size: 7253249
  object_id: 6584fd01-47ea-4cd2-75de-cf191caaa33f
  sha: sha256:5b906b1ea49c119024350c10b4b8491857a20336a0ffd778a3f10d7536a6d123
consul_exporter/consul_exporter-0.7.1.linux-amd64.tar.gz:
  size: 8030490
  object_id: 345d3576-9bfd-4c35-67d5-4731dfa65277
  sha: sha256:92ffd37fb5f2350df21e7a688c28e7bb2882c309f613400eafdc411c818ec048
credhub_exporter/credhub_exporter_0.2.2_linux_amd64.tar.gz:
  size: 3998981
  object_id: 4f062b26-2090-41fd-448c-ea669e158f5e
  sha: sha256:02d6b250c2f37999baf45aa3d7d99a7fcfdf0278e78e6f3b0947599037eaef39
elasticsearch_exporter/elasticsearch_exporter-1.2.1.linux-amd64.tar.gz:
  size: 3612042
  object_id: 46cb2f9b-de7b-4541-6496-9315e1e7bd2e
  sha: sha256:06ef2140f18f0bb6cd91b63508c81b2ce2971589454add45a1b4163d8320ff1f
firehose_exporter/firehose_exporter-6.2.0.linux-amd64.tar.gz:
  size: 9102454
  object_id: 065e08b0-0023-46ba-4955-ee5daf5e40f0
  sha: sha256:6f81a643a158a578c7e8b08e3fc06044ba957806d87c33d58955c1142cd54d8f
fontconfig/fontconfig-2.13.92.tar.gz:
  size: 2127384
  object_id: 2ff7a520-f3dd-487f-6af0-e7a7a8f758f3
  sha: sha256:3406a05b83a42231e3df68d02bc0a0cf47b3f2e8f11c8ede62267daf5f130016
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.9.1.tar.gz:
  size: 2533956
  object_id: d74e6686-1bf9-46d4-7115-1b15aa2ca41c
  sha: 7498739e34e5dca4c61d05efdde6191ba69a2df0
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-7.5.11.linux-amd64.tar.gz:
  size: 52218679
  object_id: 996ee9e3-f46f-408a-4760-dcb026d4f8cb
  sha: sha256:f6c5d1688bac8e76c84df7d22f2d858f4babb77137563d01f040b2f25b1ee0c2
grafana_plugins/flant-statusmap-panel-v0.3.4.zip:
  size: 1313699
  object_id: 647b8279-789c-42fa-5369-6f8c8d6dfb9f
  sha: sha256:9d57eebaa6590237e91c494902a29dbeb08cea2823e4ba609b05c3081d752839
grafana_plugins/grafana-clock-panel-v1.1.1.zip:
  size: 621739
  object_id: 9536cd55-c7d9-4f68-56a8-ab4b3f966eba
  sha: sha256:4af67283bafe5c6ea2ee3a98c31a4f9fa67325ceea9ad7cfb72a61629a544439
grafana_plugins/grafana-piechart-panel-v1.6.1.zip:
  size: 274360
  object_id: 1b54b9da-4c31-45af-50d5-2c94c1ced745
  sha: sha256:eb82bf79fa012ae045a7c270efd85374cc93bab4d9b0bd2a7e03c37145b3da38
grafana_plugins/grafana-worldmap-panel-v0.3.2.zip:
  size: 2681129
  object_id: 48b520b3-8b0a-4b7c-46dd-cd5656914928
  sha: sha256:306009cd2f57f75c7ac2ddf4e631f57212e85b7cddee92180f04673e0f6aae01
grafana_plugins/jdbranham-diagram-panel-v1.7.1.zip:
  size: 17352318
  object_id: 946d44a3-bc5f-494a-6246-a765899b3924
  sha: sha256:b4060059e31f02a015a177c17b71d4e3c6f7dfa3576a2f720e284ce026149ccc
grafana_plugins/mtanda-histogram-panel-v0.1.6.zip:
  size: 76062
  object_id: 52255f76-001d-4401-514b-d1ce42b82eb3
  sha: sha256:60495c5eca135fdc31530f299e2caab3389840ad8526e17a0c6e0d5934e6858b
grafana_plugins/vonage-status-panel-v1.0.10.zip:
  size: 401708
  object_id: 1d94c564-ce22-461d-6689-3d2a728fdc55
  sha: sha256:1d3ffa533def063f077415cb775bbd54ad4bd1b9f5bfe7e62250635b77dc5589
graphite_exporter/graphite_exporter-0.11.0.linux-amd64.tar.gz:
  size: 13123900
  object_id: eb24859d-6270-4d22-7c4c-e00b9ef420ea
  sha: sha256:eb8fe258889558ab419042e7cbee5fab94959055285f2434da7993d5be8f652b
haproxy_exporter/haproxy_exporter-0.12.0.linux-amd64.tar.gz:
  size: 7208819
  object_id: f018a0ce-dce2-4c51-713a-1c3d75d7249f
  sha: sha256:41d797bc7d54023ea0ea23e58be5795a0947289d3d33beab3372c52e4fcbb298
influxdb_exporter/influxdb_exporter-0.8.0.linux-amd64.tar.gz:
  size: 6325918
  object_id: 32687f5c-028f-419e-4a32-a628e9767dfe
  sha: sha256:304f0050c9697b0b8f72c94600f8c4ce67d723b2c11f272c8125c9ac55dc1912
ingestor_exporter/ingestor_exporter-2.2.0.linux-amd64.tar.gz:
  size: 5924704
  object_id: a0ce369b-0024-4b67-75ea-2bb51551d9b7
  sha: sha256:54be2bbc9f89ffbf8f70c476ec2b1835cbd619db94d18d1ae537c1a602e9b116
jq/jq-1.6.linux64:
  size: 3953824
  object_id: 04453e77-c1dd-40ad-49a8-54dedf95d8bf
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libxml2/libxml2-2.9.10.tar.gz:
  size: 5624761
  object_id: 03abdd76-bc8b-4884-7912-9b9f83462d1c
  sha: sha256:aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f
memcached_exporter/memcached_exporter-0.9.0.linux-amd64.tar.gz:
  size: 6716963
  object_id: a2473bfe-1700-4df6-4442-449f211e801e
  sha: sha256:831c59a131ca6229feff900ddb08e4337c1adaee5e91e2d6545b77166e4469a5
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.13.0.linux-amd64.tar.gz:
  size: 7242382
  object_id: c30cd778-d326-4078-7dd7-1772f7073ca0
  sha: sha256:626584c5d1c0cf09982302763e69db24fabe5dc736e7b694a3f8fdfee3d8d9a2
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.18.0.tar.gz:
  size: 1039530
  object_id: 57909d89-6f33-4d7b-6f7c-5b926dbd94fd
  sha: sha256:4c373e7ab5bf91d34a4f11a0c9496561061ba5eee6020db272a17a7228d35f99
nginx/pcre-8.44.tar.gz:
  size: 2090750
  object_id: fbee9659-eb5b-45ac-60d3-a136ef46724a
  sha: sha256:aecafd4af3bd0f3935721af77b889d9024b2e01d96b58471bd91a3063fb47728
postgres_exporter/postgres_exporter-0.10.0.linux-amd64.tar.gz:
  size: 7285638
  object_id: 0dafd93f-fe75-4e97-794a-f7b6baa10e66
  sha: sha256:1d1a008c5e29673b404a9ce119b7516fa59974aeda2f47d4a0446d102abce8a1
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.32.1.linux-amd64.tar.gz:
  size: 75073989
  object_id: 98f7f0b0-05ee-4510-4522-1775e4f610f6
  sha: sha256:f08e96d73330a9ee7e6922a9f5b72ea188988a083bbfa9932359339fcf504a74
pushgateway/pushgateway-1.4.2.linux-amd64.tar.gz:
  size: 9189846
  object_id: 094dc721-15a5-40fa-664a-0c5b10da48e0
  sha: sha256:d41df97d93a7564bf8207a8884452eb220d2124d3853682c879907c96b525a6f
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.33.0.linux-amd64.tar.gz:
  size: 3170844
  object_id: f0ea8d43-fa1f-4cae-411f-24de33ca91b5
  sha: sha256:421550c7096d23960709582d25f5c255e5e5c22b46bad3def3c64d4df3297ad1
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.11.0.linux-amd64.tar.gz:
  size: 8388191
  object_id: 580b3c8f-0f77-4dfe-647f-58c980200388
  sha: sha256:e454b260272a231228f58174f5ad042c56548d3e11a63f612ebb1c65be938b2e
statsd_exporter/statsd_exporter-0.22.2.linux-amd64.tar.gz:
  size: 6939635
  object_id: cf68ff59-2139-4db4-5203-0a92ce35ebbd
  sha: sha256:e7a3645b5302f441e16498e9b9aaca6ff1dcb5e9645821e43824560a4d6ef897
util-linux/util-linux-2.36.1.tar.gz:
  size: 11151380
  object_id: d148dc5e-357e-4f06-4261-c6cc5cc27d57
  sha: sha256:37de03dbb98cdeffdf9e754122b0aca2a9bbdc19769f6570dfcb6f123643bf53
vault_exporter/vault_exporter_0.1.2_linux_amd64.tar.gz:
  size: 3809657
  object_id: b57907a1-69f8-4e62-6708-e0e632b8ec32
  sha: 4c6e2770de08eedf96b33e9fde508d60c07aafe8
