alertmanager/alertmanager-0.27.0.linux-amd64.tar.gz:
  size: 30866868
  object_id: 0ff68b26-1e55-4a1f-69da-e1def36708ef
  sha: sha256:23c3f5a3c73de91dbaec419f3c492bef636deb02680808e5d842e6553aa16074
blackbox_exporter/blackbox_exporter-0.25.0.linux-amd64.tar.gz:
  size: 11269099
  object_id: 646a517b-1ebc-4984-52ac-3fa0af918b4a
  sha: sha256:c651ced6405c5e0cd292a400f47ae9b34f431f16c7bb098afbcd38f710144640
bosh_exporter/bosh_exporter-3.6.5.linux-amd64.tar.gz:
  size: 4847567
  object_id: 7065621e-7965-41f0-570f-258f1055d5ec
  sha: sha256:1026f3a0614ae5588c5fd8871299d8197ef8b4100a94b7104f5964c942dd84aa
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-v0.47.0-linux-amd64:
  size: 44642706
  object_id: 92e9dea2-22f4-4284-510a-a5697dc25328
  sha: sha256:caf4491298e0702f9d0c6a1d1949767f5c6400f77e12cd3524d6d3fcc66abc2a
cf_exporter/cf_exporter_1.4.0.linux-amd64.tar.gz:
  size: 7148693
  object_id: 763fc4b7-6a16-410c-590f-5089996ac0fd
  sha: sha256:dd8ea67c4318ca96bf2606101994de471fdd350c210c4858c96634c5a357c995
collectd_exporter/collectd_exporter-0.7.0.linux-amd64.tar.gz:
  size: 8865082
  object_id: d3c9e176-b121-4910-6db5-1e7017eacd82
  sha: sha256:a0410b74d7250e2f6dac2d0ca7d74ccac7813c2ceb04586e9fb262e0cd822364
consul_exporter/consul_exporter-0.13.0.linux-amd64.tar.gz:
  size: 10054358
  object_id: d4eacf74-84eb-4282-4150-b22d7d9aba7b
  sha: sha256:2a8da4147330c6e19c9665deca1c419d507e100de6c8b7c58c0715ff25453773
credhub_exporter/credhub_exporter_0.53.0_linux_amd64.tar.gz:
  size: 4424054
  object_id: a9f28b24-b518-4d27-443a-80b2a5009255
  sha: sha256:e5d6de118f1d3593878190979008f3d5ea2148f389767f8e2b1fd4b36666a434
elasticsearch_exporter/elasticsearch_exporter-1.8.0.linux-amd64.tar.gz:
  size: 5097115
  object_id: 7e1097e8-394d-49e9-4e19-6fe1b53edce7
  sha: sha256:a03a19d015c45ccc9e35f3a99c6a202b347a521a494cff0e404f9038e426135a
firehose_exporter/firehose_exporter-6.2.0.linux-amd64.tar.gz:
  size: 9102454
  object_id: 065e08b0-0023-46ba-4955-ee5daf5e40f0
  sha: sha256:6f81a643a158a578c7e8b08e3fc06044ba957806d87c33d58955c1142cd54d8f
firehose_exporter/firehose_exporter_7.1.7.linux-amd64.tar.gz:
  size: 5004039
  object_id: 5121012c-8ca2-4ec7-5171-eb92077cef68
  sha: sha256:b7cb551abc3017b305caa3ba0537d4adf98fb1da248641adcbf46f354fae6c5f
fontconfig/fontconfig-2.14.2.tar.xz:
  size: 1440844
  object_id: 7656fb30-b5c6-45ac-4d2c-48ccdca1cfbd
  sha: sha256:dba695b57bce15023d2ceedef82062c2b925e51f5d4cc4aef736cf13f60a468b
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.9.1.tar.gz:
  size: 2533956
  object_id: d74e6686-1bf9-46d4-7115-1b15aa2ca41c
  sha: 7498739e34e5dca4c61d05efdde6191ba69a2df0
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-10.4.14.linux-amd64.tar.gz:
  size: 118080553
  sha: sha256:398fc724ba8b8ec388d9a80d211980c6b75a7575e445f0d25c61bec161c25ba3
grafana_plugins/flant-statusmap-panel-0.5.1.zip:
  size: 289519
  object_id: 1c011a4e-29fb-4081-4c58-947735d9bb9f
  sha: sha256:6841f3687f70711673766646aca3a2bb2d28a8e2e6336370329c90d917beb5a9
grafana_plugins/grafana-clock-panel-2.1.7.zip:
  size: 484838
  object_id: 49e03fe9-a969-4368-50d0-3da47cdeaf9a
  sha: sha256:9ed9f4082c5e3c1d2146fbf383ad56b39f651053dd72dfe0ea37467df4a2a428
grafana_plugins/grafana-worldmap-panel-v1.0.6.zip:
  size: 1089481
  object_id: b385e208-fa32-4f0b-5131-c4301d79c230
  sha: sha256:9321d77b64d29404a1c9e62bfc136a71f8db17f5cf65827e972c94fbe619f94d
grafana_plugins/jdbranham-diagram-panel-1.10.4.zip:
  size: 6446989
  object_id: 71658584-b01e-42ee-7b16-5bd775ff5ce4
  sha: sha256:f95b691d0a73da8910145d958bc6e59ed66b47a26cf7cf07bb41f057ff2a5a66
grafana_plugins/mtanda-histogram-panel-v0.1.6.zip:
  size: 76062
  object_id: 52255f76-001d-4401-514b-d1ce42b82eb3
  sha: sha256:60495c5eca135fdc31530f299e2caab3389840ad8526e17a0c6e0d5934e6858b
grafana_plugins/vonage-status-panel-v1.0.10.zip:
  size: 401708
  object_id: 1d94c564-ce22-461d-6689-3d2a728fdc55
  sha: sha256:1d3ffa533def063f077415cb775bbd54ad4bd1b9f5bfe7e62250635b77dc5589
graphite_exporter/graphite_exporter-0.16.0.linux-amd64.tar.gz:
  size: 22242517
  object_id: 40283104-d085-4004-69a1-75c2b0c9c03d
  sha: sha256:129acf14bb62dc32596ff8aed40a526a66260b2736801bc546be407436dd32d8
haproxy_exporter/haproxy_exporter-0.15.0.linux-amd64.tar.gz:
  size: 8197764
  object_id: 3c1ec2f4-e971-4012-627b-f0ba993b35c5
  sha: sha256:ac200872b734e2f9c0211997f7f9c0ca5ad6522996c37aed39a732d5f3c0de16
influxdb_exporter/influxdb_exporter-0.12.0.linux-amd64.tar.gz:
  size: 7852845
  object_id: 56c13032-b2a4-4d6d-611b-ef64ecdcaa72
  sha: sha256:1b00556c5aebcf70654ef96a0e0fe301dd7867a1864004986188d966a27f4fa1
ingestor_exporter/ingestor_exporter-2.2.0.linux-amd64.tar.gz:
  size: 5924704
  object_id: a0ce369b-0024-4b67-75ea-2bb51551d9b7
  sha: sha256:54be2bbc9f89ffbf8f70c476ec2b1835cbd619db94d18d1ae537c1a602e9b116
jq/jq-1.6.linux64:
  size: 3953824
  object_id: 04453e77-c1dd-40ad-49a8-54dedf95d8bf
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libxml2/libxml2-2.11.0.tar.xz:
  size: 2617968
  object_id: 0a3bc78d-7958-4c64-613d-d9d376cde373
  sha: sha256:b1a2fca3f7722d6c35a4f24974a1b5800e4d84ec5cb756bc61ef2b8c75a19e36
memcached_exporter/memcached_exporter-0.15.0.linux-amd64.tar.gz:
  size: 8853661
  object_id: 3e2ab277-34ff-49f8-69b5-e62d62bae721
  sha: sha256:d628bd8119b8e69696f61bdf6736490962d5abd52d35207b58a547447aa4e74f
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.16.0.linux-amd64.tar.gz:
  size: 9458882
  object_id: 4ecab4ec-741a-4415-6881-8a737a92055a
  sha: sha256:32fe0b59ef3f52624a1958aaf6b8855f27c2b492a7026d62a975bbd251be209d
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.25.3.tar.gz:
  size: 1216580
  object_id: 92880be7-cbb0-4ca3-6f55-251d2b2a6bd3
  sha: sha256:64c5b975ca287939e828303fa857d22f142b251f17808dfe41733512d9cded86
nginx/pcre-8.45.tar.gz:
  size: 2096552
  object_id: 07d80377-8e45-4f83-7d5b-47c2df280efb
  sha: sha256:4e6ce03e0336e8b4a3d6c2b70b1c5e18590a5673a98186da90d4f33c23defc09
postgres_exporter/postgres_exporter-0.16.0.linux-amd64.tar.gz:
  size: 9712128
  object_id: 752d9bb7-0ea6-469c-538b-ccdf83c6811a
  sha: sha256:5763bd10108e9739e7857377deeb43d2addf07c4c4f4d4c882a08847c15bfd61
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.55.0.linux-amd64.tar.gz:
  size: 111627572
  object_id: 6f917c12-a816-4586-781f-0d90a41611a7
  sha: sha256:7a6b6d5ea003e8d59def294392c64e28338da627bf760cf268e788d6a8832a23
pushgateway/pushgateway-1.10.0.linux-amd64.tar.gz:
  size: 11342069
  object_id: d9f59d39-a8fe-46bd-4b29-1d2d909d50df
  sha: sha256:e2310c978da19362f2c7f91668550fdbbbb7421f7dfc8eb81a927e017f7b8d17
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.67.0.linux-amd64.tar.gz:
  size: 3585567
  object_id: c766ead2-064a-46bb-5a99-ab03853fbd7f
  sha: sha256:32c5ac73b128f1463e311e639b061704fb8b84c9469d0bfef4ee4a2d920457cd
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.17.0.linux-amd64.tar.gz:
  size: 12256043
  object_id: c5a49a53-279c-4667-508c-bb73f855274a
  sha: sha256:f47b0270983fa0e7cf99fd8d9697fa1467fef6167ce42ff8209448a72824ccdf
statsd_exporter/statsd_exporter-0.28.0.linux-amd64.tar.gz:
  size: 9097691
  object_id: d79da327-a1dd-4016-7563-b3e3abb4929f
  sha: sha256:6951081e3115669e4353975f897dda1cefddef5a5d16addc908485d9be16b72b
util-linux/util-linux-2.38.1.tar.xz:
  size: 7495904
  object_id: 5cf63a34-123f-422f-5a62-0e2b64254471
  sha: sha256:60492a19b44e6cf9a3ddff68325b333b8b52b6c59ce3ebd6a0ecaa4c5117e84f
vault_exporter/vault_exporter_0.1.3_linux_amd64.tar.gz:
  size: 3773592
  object_id: 75bd13c6-4452-447a-6847-9f82599ef36d
  sha: sha256:26d0f36233270bb0ede98da94c2cdad09180cbadd7ee4ae3205961d13e9b7c55
