alertmanager/alertmanager-0.11.0.linux-amd64.tar.gz:
  size: 9471710
  object_id: 7ba1a423-31bf-4f76-5591-e23fc14282d9
  sha: 822fa1ff011957a9feb84d0c747e46fe0af0b986
blackbox_exporter/blackbox_exporter-0.11.0.linux-amd64.tar.gz:
  size: 4566957
  object_id: 336922f7-5786-4f10-6ec3-d0a660867f90
  sha: 49160bd5368ed4a86d78b1bdfd9a5fcb9d1b69b4
bosh_exporter/bosh_exporter-2.4.5.linux-amd64.tar.gz:
  size: 4411198
  object_id: 0dab2e87-a602-4eda-5bcb-cff937ceb569
  sha: 5ec3bd199964e1bcf029c1f96c4fcf43b86bf687
bosh_tsdb_exporter/bosh_tsdb_exporter-0.1.1.linux-amd64.tar.gz:
  size: 3531789
  object_id: 2a45dc94-e31e-48ff-762e-158480dd345d
  sha: b09e52e8d4ccbbba58594099095b457eae928ef6
cadvisor/cadvisor-0.27.2.tar.gz:
  size: 7082445
  object_id: d872172e-508c-4161-7c69-ff771e70bb4f
  sha: 7764d4f97a69ae0aa8aca4d7a3546d26ac2ca717
cf_exporter/cf_exporter-0.5.2.linux-amd64.tar.gz:
  size: 3825766
  object_id: 8ae1d3aa-4ba7-4b32-75fc-5edda6a86603
  sha: 18201d3b6f29aafed5058da13d83368dccffb1f4
collectd_exporter/collectd_exporter-0.3.1.linux-amd64.tar.gz:
  size: 3192169
  object_id: 36973f70-cc64-4a0f-a30f-60ec36786506
  sha: 6460a15dab512f7485d7974d115677e9406d53fd
consul_exporter/consul_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3445115
  object_id: 600dab52-4792-4ddf-b95e-e3c74644e730
  sha: 8df96252a2d5409554799dda600648263ffca668
elasticsearch_exporter/elasticsearch_exporter-1.0.1.linux-amd64.tar.gz:
  size: 1980695
  object_id: 7b2a10b4-44b3-44fd-4012-b67055787b00
  sha: 31d55a852528aa4f050ad24c731d8e66752ed7d7
firehose_exporter/firehose_exporter-4.2.6.linux-amd64.tar.gz:
  size: 4217867
  object_id: 82ffbde2-d1fc-4fbd-75df-7961d814c796
  sha: 6b2b17fac622f7d3071101c0314ad2e2b3b8ea1d
fontconfig/fontconfig-2.12.6.tar.gz:
  size: 1927653
  object_id: bdabccd6-065a-4476-52d4-8f0db816c3f4
  sha: d5de50c30317cf20e86c49b4aa25175e0ad9b8e8
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.8.1.tar.gz:
  size: 2505539
  object_id: 34f25172-770b-48b1-487b-ade53aaf8d06
  sha: 421e1cc3a7ef026002c2739ce412eed46e3454fe
golang/go1.9.2.linux-amd64.tar.gz:
  size: 104247844
  object_id: 04dbf815-06f3-46e9-67f7-ce1d10864e2a
  sha: 94c889e039e3d2e94ed95e8f8cb747c5bc1c2b58
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-4.6.2.linux-x64.tar.gz:
  size: 47182881
  object_id: 7aa68982-e0e6-49da-550f-c42a8add242e
  sha: ee8bd0964b736f01f6b60edb755d1457c9c33de1
graphite_exporter/graphite_exporter-0.2.0.linux-amd64.tar.gz:
  size: 2954303
  object_id: 85cfd62e-a033-4579-8a46-b2b774b09fd4
  sha: 89c32d0f324a708eb08a5594d4dcaa97861264fd
haproxy_exporter/haproxy_exporter-0.8.0.linux-amd64.tar.gz:
  size: 3595674
  object_id: ab118be6-6f81-492a-4127-3e24d59bb409
  sha: 88737c1fd658fda8aa043d560f4615fba173f72a
influxdb_exporter/influxdb_exporter-0.1.0.linux-amd64.tar.gz:
  size: 3142981
  object_id: ae490a76-5c1d-47f0-58a4-b013026d87eb
  sha: 307fad2efa2196b31ce3f7f88a352b8079cd16a1
jq/jq-1.5.linux64:
  size: 3027945
  object_id: ed1530a7-c4f4-45c1-83b2-8dd00ecf00a6
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
memcached_exporter/memcached_exporter-0.3.0.linux-amd64.tar.gz:
  size: 2987032
  object_id: 60f81117-ddac-42de-a31c-0dae620a7a06
  sha: a2b5ac549f8fdd81181bf9fe79959bae812e3849
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.10.0.linux-amd64.tar.gz:
  size: 3397781
  object_id: cee793bf-1d40-4c23-9ce3-ecc0ce16dbbe
  sha: 5c3bfac700be7914eb3dafccfa60928a6d88ef8c
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.10.3.tar.gz:
  size: 911509
  object_id: 67ae929d-3830-4096-883e-970a9be4e65a
  sha: 95cf32c3e33efc53ac81338a5779fbaa425f02e2
nginx/pcre-8.41.tar.gz:
  size: 2068775
  object_id: f8531763-ed41-4a92-7671-388c110a440b
  sha: dddf0995aefe04cc6267c1448ffef0e7b0560ec0
postgres_exporter/postgres_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3010743
  object_id: 6f12c48f-79cb-4bf2-4702-dee77c278ce3
  sha: 889827008191680122f9ea8aaaef5459469ce141
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.0.0.linux-amd64.tar.gz:
  size: 18850224
  object_id: bf96439b-f2e7-475d-6918-59545da19e89
  sha: 5e62b47751b070fc6c86e15034e437887f305dfa
pushgateway/pushgateway-0.4.0.linux-amd64.tar.gz:
  size: 3723718
  object_id: ee0677f0-7049-4167-4f76-a155766f1ab6
  sha: dcf0533c563de8647e5d18d3c4074c96a8817cf4
python/Python-3.6.1.tgz:
  size: 22540566
  object_id: 3f4a2f27-fb40-410f-a582-722671c79c17
  sha: 6e91434cf22414af8240dfa1bf8ab2d043b04998
python/pip-9.0.1.tar.gz:
  size: 1197370
  object_id: 6ed5c7b3-88fc-4336-bf52-8c321e66d5ea
  sha: 57ff41e99cb01b6a1c2b0999161589b726f0ec8b
python/prometheus_client-0.0.19.tar.gz:
  size: 20496
  object_id: b78d1798-0807-42bd-a224-f5af0982cf6b
  sha: 833563d11353b313308c4efe8200d40f4fb232f7
python/requests-2.13.0.tar.gz:
  size: 557508
  object_id: a030860b-cfd3-40f8-afa2-287e6b3f418a
  sha: 827f7c8abb5a57d980d9870908724613b8b120c1
python/setuptools-34.4.1.tar.gz:
  size: 578407
  object_id: 79159c7c-e269-45c8-b413-db79b35ea4ce
  sha: 0225b6f5eb97799efdea6e3eeae24a2e385b5d53
rabbitmq_exporter/rabbitmq_exporter-0.25.0.linux-amd64.tar.gz:
  size: 2786829
  object_id: 0e4a6e6a-dc79-4103-57cf-ed434d4032f5
  sha: aa6adad338964ced33f49fa4fa985940565b8f5f
redis_exporter/redis_exporter-v0.14.linux-amd64.tar.gz:
  size: 2801052
  object_id: 201f8a2f-1b6f-4231-48fb-812c25956169
  sha: e67d99add90935b63a3bda6c9b50596ba8dd1aaa
shield_exporter/shield_exporter-0.2.2.linux-amd64.tar.gz:
  size: 3704693
  object_id: 484a5fc9-0d7b-48fe-55d8-834347acd64d
  sha: 61ccbe358d8379395ad68247c64f3827388b5cd4
stackdriver_exporter/stackdriver_exporter-0.4.1.linux-amd64.tar.gz:
  size: 3248456
  object_id: f66d2653-c5f4-463e-6d67-04cff081bebb
  sha: f555698b4dfcc66831d3bfde0d638bd18c79ff54
statsd_exporter/statsd_exporter-0.5.0.linux-amd64.tar.gz:
  size: 3675167
  object_id: 52971b10-dda0-48f4-739c-c151fa971ada
  sha: 3428518a013751b8aa61f6f267eac78e42913eb5
