alertmanager/alertmanager-0.19.0.linux-amd64.tar.gz:
  size: 24201990
  object_id: 07b5dc7e-4dec-4a09-7cc6-65c28b5fcb72
  sha: sha256:6191788f8b91a05955fcdc2ab4bc7d0edf70e5039f3acffb284d75745cc80d67
blackbox_exporter/blackbox_exporter-0.15.1.linux-amd64.tar.gz:
  size: 8308336
  object_id: a6a79b64-d9dd-4762-7a89-d2127c6652a7
  sha: sha256:73a702f03f9955c2469226c33a35df7fc22f3051663166f10458f220dc48b8f9
bosh_exporter/bosh_exporter-3.3.0.linux-amd64.tar.gz:
  size: 7951925
  object_id: 1cb948b8-aa67-4af5-75f0-bfdf6fb2dc8f
  sha: sha256:7a998ab28b8c4b2ba075f72a580d608a346478fe9b64725ea767997bd7a6f916
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-0.33.0.tar.gz:
  size: 13168486
  object_id: 258d11ca-130e-4e0f-468d-4ab43e2e437c
  sha: sha256:a3a936a665ad93160b9b032887b6580d9cef5d3d621df637cee1b49e4447a252
cf_exporter/cf_exporter-0.10.0.linux-amd64.tar.gz:
  size: 7127668
  object_id: b283e6e7-0df3-48d6-663c-ace280fbea64
  sha: sha256:d5ac3d8ecc76d4f0c28e0ab3f5422357227ad56aae9801aa19316390d62df001
collectd_exporter/collectd_exporter-0.4.0.linux-amd64.tar.gz:
  size: 3340495
  object_id: 428779f0-9ae9-4a9b-6a53-9207c416cf14
  sha: 56c122cb29777e77f7db008b5e6bd49de35060b0
consul_exporter/consul_exporter-0.5.0.linux-amd64.tar.gz:
  size: 7195164
  object_id: bc6354dc-6803-4185-6dce-43e2afae108c
  sha: sha256:4592b3e0e1b1f1ed18bd2a95a19016feb081bb0eb304d6e48cbbae030aee7805
credhub_exporter/credhub_exporter-0.1.6.linux-amd64.tar.gz:
  size: 6227648
  object_id: 0ae6c921-30ff-457e-40a2-fa04a14886f9
  sha: 1fe502186faa6c85be1ae3a3d55aec5cab247867
elasticsearch_exporter/elasticsearch_exporter-1.1.0.linux-amd64.tar.gz:
  size: 3632462
  object_id: 985f1a9f-9883-48c0-6f05-8e739db410a5
  sha: sha256:1d2444d7cbf321cb31d58d2fecc08c8bc90bbcec581f8a1ddb987f9ef425482b
firehose_exporter/firehose_exporter-6.1.0.linux-amd64.tar.gz:
  size: 9092157
  object_id: 879c7a3f-3fc0-4180-563b-52ae1511a3af
  sha: sha256:4e02b9998c72b7fe3d69a3db474bb6feb544f95751653f4b6a1fced3fb4144f2
fontconfig/fontconfig-2.13.92.tar.gz:
  size: 2127384
  object_id: 2ff7a520-f3dd-487f-6af0-e7a7a8f758f3
  sha: sha256:3406a05b83a42231e3df68d02bc0a0cf47b3f2e8f11c8ede62267daf5f130016
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.9.1.tar.gz:
  size: 2533956
  object_id: d74e6686-1bf9-46d4-7115-1b15aa2ca41c
  sha: 7498739e34e5dca4c61d05efdde6191ba69a2df0
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-6.3.4.linux-amd64.tar.gz:
  size: 58756149
  object_id: ebec876a-67b1-4654-7a56-55b6dd9b1cb8
  sha: sha256:88315d8204157755abf8661e6ee66b62eefee080007716892146479ed9f00e52
graphite_exporter/graphite_exporter-0.6.2.linux-amd64.tar.gz:
  size: 6918576
  object_id: 823ea501-25c1-404a-5e66-7d131c9308b0
  sha: sha256:9b962bd06406ece4a865ad6947a6e652e48a92a0d77e496a0351c04e9c2c5e9e
haproxy_exporter/haproxy_exporter-0.10.0.linux-amd64.tar.gz:
  size: 5975717
  object_id: 7e2d5da9-a10d-4601-67dc-995b803a97b2
  sha: 7f47a9205e84f6ca115e67cea953975c3d9c4a1e
influxdb_exporter/influxdb_exporter-0.3.0.linux-amd64.tar.gz:
  size: 6327430
  object_id: 9d9205f4-3d01-4e57-4fb9-30461b2be62f
  sha: sha256:0267cad0f40a961960679b711f28f839950dc55ac0c05fd11a475d2289abc618
jq/jq-1.6.linux64:
  size: 3953824
  object_id: 04453e77-c1dd-40ad-49a8-54dedf95d8bf
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libxml2/libxml2-2.9.9.tar.gz:
  size: 5476717
  object_id: c8cecac6-6d78-4753-70a4-05dbcc3f19ae
  sha: sha256:94fb70890143e3c6549f265cee93ec064c80a84c42ad0f23e85ee1fd6540a871
memcached_exporter/memcached_exporter-0.6.0.linux-amd64.tar.gz:
  size: 6531705
  object_id: c064ec3e-0342-46c4-6ca2-ed31a01c8bae
  sha: sha256:20382d37ca99bbde2661fdbfb43a181f95d68889b761e56b39678e31bb23b64c
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.12.1.linux-amd64.tar.gz:
  size: 7121565
  object_id: 3e8d5841-8c2e-44af-40cd-efa31f3473cc
  sha: sha256:133b0c281e5c6f8a34076b69ade64ab6cac7298507d35b96808234c4aa26b351
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.16.1.tar.gz:
  size: 1032630
  object_id: 260514ec-ee20-467d-485f-c86e103a7d75
  sha: sha256:f11c2a6dd1d3515736f0324857957db2de98be862461b5a542a3ac6188dbe32b
nginx/pcre-8.43.tar.gz:
  size: 2085854
  object_id: 3653d041-229c-42ca-6df0-4e2485393c1b
  sha: sha256:0b8e7465dc5e98c757cc3650a20a7843ee4c3edf50aaf60bb33fd879690d2c73
postgres_exporter/postgres_exporter_v0.5.1_linux-amd64.tar.gz:
  size: 5922452
  object_id: d9440f55-f807-4888-54d3-ed1b65b30c00
  sha: sha256:7b00cc56d83e3a8f5a58d2b0f17f12b1b3b1b1ecccffffc3e8446ff187058c0e
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.12.0.linux-amd64.tar.gz:
  size: 53127635
  object_id: a8c54581-f234-4f4d-5e41-701dcacee34b
  sha: sha256:b9f57b6e64fb3048742cfa7dbcc727e1df906d8020ef246a5e81b7959ae97e08
pushgateway/pushgateway-0.9.1.linux-amd64.tar.gz:
  size: 8823528
  object_id: 0dfd86d9-8128-4466-4f39-419ce4d5058f
  sha: sha256:6741f8e8f4d728a907991c7a9f0a7e32e1e9cf339a9795724412e54466f2e8e1
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.1.0.linux-amd64.tar.gz:
  size: 3331788
  object_id: 35fb5264-4c26-4905-4ca1-3b505c89f91f
  sha: sha256:0da0ec6d71a74955457da34d551b5dc2dfc0e5b06dbd4d5b718db35eb5ad51db
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.6.0.linux-amd64.tar.gz:
  size: 5755060
  object_id: fa8a4c12-567d-4e94-530a-24a756879a34
  sha: e4adf3ca00920d705dcfe369d50272ba3f9bf1c5
statsd_exporter/statsd_exporter-0.12.2.linux-amd64.tar.gz:
  size: 7084732
  object_id: 0ebffdec-d094-407a-6549-5233e6437f62
  sha: sha256:9976810ae7a0e3593d6727d46d8c45a23f534e5794de816ed8309a42bb86cb34
util-linux/util-linux-2.34.tar.gz:
  size: 10511467
  object_id: 4cf4cdd0-39ef-4fb6-7249-003639525e85
  sha: sha256:b62c92e5e1629642113cd41cec1ee86d1ee7e36b8ffe8ec3ac89c11797e9ac25
vault_exporter/vault_exporter_0.1.2_linux_amd64.tar.gz:
  size: 3809657
  object_id: b57907a1-69f8-4e62-6708-e0e632b8ec32
  sha: 4c6e2770de08eedf96b33e9fde508d60c07aafe8
