alertmanager/alertmanager-0.21.0.linux-amd64.tar.gz:
  size: 25710888
  object_id: 849441c5-b56b-42ff-6262-8fa31c5b8cc8
  sha: sha256:9ccd863937436fd6bfe650e22521a7f2e6a727540988eef515dde208f9aef232
blackbox_exporter/blackbox_exporter-0.18.0.linux-amd64.tar.gz:
  size: 8884083
  object_id: 9c0a48f1-d636-4d51-79d4-64cfbfa1cd14
  sha: sha256:a87f9530e31e2b20d03a6d941f6f051c57ee724f24b38f2615b8580ca63966dc
bosh_exporter/bosh_exporter-3.3.0.linux-amd64.tar.gz:
  size: 7951925
  object_id: 1cb948b8-aa67-4af5-75f0-bfdf6fb2dc8f
  sha: sha256:7a998ab28b8c4b2ba075f72a580d608a346478fe9b64725ea767997bd7a6f916
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-0.37.0.tar.gz:
  size: 16905721
  object_id: 9d353079-a632-4033-4c98-eda68a05eb93
  sha: sha256:07e2f631fb99d058d7d783d457fdb3039c4dbd49a87b2be64143849031b89fe2
cf_exporter/cf_exporter-0.10.1.linux-amd64.tar.gz:
  size: 7345936
  object_id: d6639464-cc47-4a19-6e24-8533e8094184
  sha: sha256:f161c1410e40e2912b55aa80d252fd08fb839282c1f20a9a4f0a812ff7cc5a43
collectd_exporter/collectd_exporter-0.5.0.linux-amd64.tar.gz:
  size: 7253249
  object_id: 6584fd01-47ea-4cd2-75de-cf191caaa33f
  sha: sha256:5b906b1ea49c119024350c10b4b8491857a20336a0ffd778a3f10d7536a6d123
consul_exporter/consul_exporter-0.7.1.linux-amd64.tar.gz:
  size: 8030490
  object_id: 345d3576-9bfd-4c35-67d5-4731dfa65277
  sha: sha256:92ffd37fb5f2350df21e7a688c28e7bb2882c309f613400eafdc411c818ec048
credhub_exporter/credhub_exporter_0.2.2_linux_amd64.tar.gz:
  size: 3998981
  object_id: 4f062b26-2090-41fd-448c-ea669e158f5e
  sha: sha256:02d6b250c2f37999baf45aa3d7d99a7fcfdf0278e78e6f3b0947599037eaef39
elasticsearch_exporter/elasticsearch_exporter-1.1.0.linux-amd64.tar.gz:
  size: 3632462
  object_id: 985f1a9f-9883-48c0-6f05-8e739db410a5
  sha: sha256:1d2444d7cbf321cb31d58d2fecc08c8bc90bbcec581f8a1ddb987f9ef425482b
firehose_exporter/firehose_exporter-6.2.0.linux-amd64.tar.gz:
  size: 9102454
  object_id: 065e08b0-0023-46ba-4955-ee5daf5e40f0
  sha: sha256:6f81a643a158a578c7e8b08e3fc06044ba957806d87c33d58955c1142cd54d8f
fontconfig/fontconfig-2.13.92.tar.gz:
  size: 2127384
  object_id: 2ff7a520-f3dd-487f-6af0-e7a7a8f758f3
  sha: sha256:3406a05b83a42231e3df68d02bc0a0cf47b3f2e8f11c8ede62267daf5f130016
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.9.1.tar.gz:
  size: 2533956
  object_id: d74e6686-1bf9-46d4-7115-1b15aa2ca41c
  sha: 7498739e34e5dca4c61d05efdde6191ba69a2df0
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-7.3.3.linux-amd64.tar.gz:
  size: 53921906
  object_id: fc026398-2239-45d9-51ad-f72a31613ab6
  sha: sha256:f0c8ec488301a4e5b948192de6c57a7adde6233f292d4fd5363bc88395a57f79
grafana_plugins/flant-statusmap-panel-v0.3.4.zip:
  size: 1313699
  object_id: 647b8279-789c-42fa-5369-6f8c8d6dfb9f
  sha: sha256:9d57eebaa6590237e91c494902a29dbeb08cea2823e4ba609b05c3081d752839
grafana_plugins/grafana-clock-panel-v1.1.1.zip:
  size: 621739
  object_id: 9536cd55-c7d9-4f68-56a8-ab4b3f966eba
  sha: sha256:4af67283bafe5c6ea2ee3a98c31a4f9fa67325ceea9ad7cfb72a61629a544439
grafana_plugins/grafana-piechart-panel-v1.6.1.zip:
  size: 274360
  object_id: 1b54b9da-4c31-45af-50d5-2c94c1ced745
  sha: sha256:eb82bf79fa012ae045a7c270efd85374cc93bab4d9b0bd2a7e03c37145b3da38
grafana_plugins/grafana-worldmap-panel-v0.3.2.zip:
  size: 2681129
  object_id: 48b520b3-8b0a-4b7c-46dd-cd5656914928
  sha: sha256:306009cd2f57f75c7ac2ddf4e631f57212e85b7cddee92180f04673e0f6aae01
grafana_plugins/jdbranham-diagram-panel-v1.7.1.zip:
  size: 17352318
  object_id: 946d44a3-bc5f-494a-6246-a765899b3924
  sha: sha256:b4060059e31f02a015a177c17b71d4e3c6f7dfa3576a2f720e284ce026149ccc
grafana_plugins/mtanda-histogram-panel-v0.1.6.zip:
  size: 76062
  object_id: 52255f76-001d-4401-514b-d1ce42b82eb3
  sha: sha256:60495c5eca135fdc31530f299e2caab3389840ad8526e17a0c6e0d5934e6858b
grafana_plugins/vonage-status-panel-v1.0.10.zip:
  size: 401708
  object_id: 1d94c564-ce22-461d-6689-3d2a728fdc55
  sha: sha256:1d3ffa533def063f077415cb775bbd54ad4bd1b9f5bfe7e62250635b77dc5589
graphite_exporter/graphite_exporter-0.9.0.linux-amd64.tar.gz:
  size: 7791001
  object_id: 5189072b-5a0f-49c0-7393-d19cdec51970
  sha: sha256:8da5bf07180f345abbd0e3c5ddf0f2bd319d930b6f9dd0385f4cfebdc6815c86
haproxy_exporter/haproxy_exporter-0.11.0.linux-amd64.tar.gz:
  size: 7525441
  object_id: 5548d0e1-3e56-4c60-74aa-7d798ac7edd6
  sha: sha256:525ec4684b33a7fd1b23fe39e5c378e09cbc52b56fb3e203cffa26e09d22d10d
influxdb_exporter/influxdb_exporter-0.6.0.linux-amd64.tar.gz:
  size: 6342574
  object_id: c282b0bd-97a9-49ba-62af-e910d3be00d4
  sha: sha256:2c2f87e99b9e77257de4d842347ce419e59bed193b9d502670a8ed4ed9204ae6
ingestor_exporter/ingestor_exporter-2.2.0.linux-amd64.tar.gz:
  size: 5924704
  object_id: a0ce369b-0024-4b67-75ea-2bb51551d9b7
  sha: sha256:54be2bbc9f89ffbf8f70c476ec2b1835cbd619db94d18d1ae537c1a602e9b116
jq/jq-1.6.linux64:
  size: 3953824
  object_id: 04453e77-c1dd-40ad-49a8-54dedf95d8bf
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libxml2/libxml2-2.9.10.tar.gz:
  size: 5624761
  object_id: 03abdd76-bc8b-4884-7912-9b9f83462d1c
  sha: sha256:aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f
memcached_exporter/memcached_exporter-0.7.0.linux-amd64.tar.gz:
  size: 7068524
  object_id: 63ba9734-afc4-48e4-7d70-6136539068ba
  sha: sha256:a8dec3f2493330159b02ab5f8916726d2d41d70170f23206b1987cdb450a839b
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.12.1.linux-amd64.tar.gz:
  size: 7121565
  object_id: 3e8d5841-8c2e-44af-40cd-efa31f3473cc
  sha: sha256:133b0c281e5c6f8a34076b69ade64ab6cac7298507d35b96808234c4aa26b351
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.18.0.tar.gz:
  size: 1039530
  object_id: 57909d89-6f33-4d7b-6f7c-5b926dbd94fd
  sha: sha256:4c373e7ab5bf91d34a4f11a0c9496561061ba5eee6020db272a17a7228d35f99
nginx/pcre-8.44.tar.gz:
  size: 2090750
  object_id: fbee9659-eb5b-45ac-60d3-a136ef46724a
  sha: sha256:aecafd4af3bd0f3935721af77b889d9024b2e01d96b58471bd91a3063fb47728
postgres_exporter/postgres_exporter_v0.8.0_linux-amd64.tar.gz:
  size: 6016522
  object_id: 5c554234-7e77-43a3-51fd-1c1032cb710a
  sha: sha256:272ed14d3c360579d6e231db34a568ec08f61d2e163cf111e713929ffb6db3f5
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.26.1.linux-amd64.tar.gz:
  size: 65179092
  sha: sha256:fe16026d37a69ac195176096d3629ac6b3d1b553b5d9f0bd723b607a8b311707
pushgateway/pushgateway-1.3.0.linux-amd64.tar.gz:
  size: 9061204
  object_id: 851df208-d52b-42d1-6931-f557f017c1cd
  sha: sha256:1ea7260a41c710a5b0f8ca1b90d18e70afdcc98ce23de61f88aba79a73d85947
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.13.1.linux-amd64.tar.gz:
  size: 3241167
  object_id: 9833e71b-87e1-4489-471d-456220b8d166
  sha: sha256:3bd576e873ecac54ae07100c1441099f2fac9802c63a6c3bd33a0110a156f66f
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.11.0.linux-amd64.tar.gz:
  size: 8388191
  object_id: 580b3c8f-0f77-4dfe-647f-58c980200388
  sha: sha256:e454b260272a231228f58174f5ad042c56548d3e11a63f612ebb1c65be938b2e
statsd_exporter/statsd_exporter-0.18.0.linux-amd64.tar.gz:
  size: 7965158
  object_id: b0c3dd1a-eef3-433e-74ec-ca01ce3e32ff
  sha: sha256:d06793bd984a67e5cbead82b74e0a0f7bcd2518914ba243ab63ff8e8da532ca5
util-linux/util-linux-2.36.1.tar.gz:
  size: 11151380
  object_id: d148dc5e-357e-4f06-4261-c6cc5cc27d57
  sha: sha256:37de03dbb98cdeffdf9e754122b0aca2a9bbdc19769f6570dfcb6f123643bf53
vault_exporter/vault_exporter_0.1.2_linux_amd64.tar.gz:
  size: 3809657
  object_id: b57907a1-69f8-4e62-6708-e0e632b8ec32
  sha: 4c6e2770de08eedf96b33e9fde508d60c07aafe8
