alertmanager/alertmanager-0.24.0.linux-amd64.tar.gz:
  size: 25880024
  object_id: c0e0f0f1-c7e5-4a80-4690-6e5e50de3552
  sha: sha256:6fa982232ae7be5524f5b3cd4e90b7c6a75086368200c917644eaa3e806555dc
blackbox_exporter/blackbox_exporter-0.23.0.linux-amd64.tar.gz:
  size: 10831812
  object_id: 8e7cd3ed-33bb-482c-411e-91f4b36745e1
  sha: sha256:63bd4fde6984db79c95e1502a0ab47da6194d763bff22a04d1f50c4fd8322b84
bosh_exporter/bosh_exporter-3.4.0.linux-amd64.tar.gz:
  size: 7727120
  object_id: df3639b9-15d4-4856-6ae1-35dfefac87c9
  sha: sha256:3d9cd96367d35cf4258c90f637f9778711b1c252c00661bd30d5e60ee3e38478
bosh_tsdb_exporter/bosh_tsdb_exporter-0.2.0.linux-amd64.tar.gz:
  size: 3517628
  object_id: 803f9cdf-4cc8-4dcf-4be4-1811ae11a6c8
  sha: a76c831d007b2097fe47a3bb2db7ed249d122c79
cadvisor/cadvisor-v0.46.0-linux-amd64:
  size: 29
  object_id: 036b5e7f-22a0-47f9-7935-bb49a6f34a34
  sha: sha256:3cd8cda66399b60836a3e08ad0ec596a8650e4ff584736e0631e653229804e95
cf_exporter/cf_exporter-0.10.1.linux-amd64.tar.gz:
  size: 7345936
  object_id: d6639464-cc47-4a19-6e24-8533e8094184
  sha: sha256:f161c1410e40e2912b55aa80d252fd08fb839282c1f20a9a4f0a812ff7cc5a43
collectd_exporter/collectd_exporter-0.5.0.linux-amd64.tar.gz:
  size: 7253249
  object_id: 6584fd01-47ea-4cd2-75de-cf191caaa33f
  sha: sha256:5b906b1ea49c119024350c10b4b8491857a20336a0ffd778a3f10d7536a6d123
consul_exporter/consul_exporter-0.9.0.linux-amd64.tar.gz:
  size: 8799847
  object_id: ae47c543-ad44-499a-6478-d976c4d1aae5
  sha: sha256:918bbbfaec650a9a1159edc663c7b09d6477cd96c078edef6d9fe608ece3c4ff
credhub_exporter/credhub_exporter_0.18.0_linux_amd64.tar.gz:
  size: 4137867
  object_id: 67c5753b-3b36-46b6-45d1-f5a4eeb1308d
  sha: sha256:4139f685db3c9e0e9a6baa2956e00348c9f010ed5ed38a1e5f987fe6c8223d12
elasticsearch_exporter/elasticsearch_exporter-1.5.0.linux-amd64.tar.gz:
  size: 4394851
  object_id: b502c37b-fed4-4c80-7d34-77ff079e8c66
  sha: sha256:66dfe9981e860c9f068f04fb82659da1ddcf9a4581d579f79d9febf431b05ac7
firehose_exporter/firehose_exporter-6.2.0.linux-amd64.tar.gz:
  size: 9102454
  object_id: 065e08b0-0023-46ba-4955-ee5daf5e40f0
  sha: sha256:6f81a643a158a578c7e8b08e3fc06044ba957806d87c33d58955c1142cd54d8f
fontconfig/fontconfig-2.13.92.tar.gz:
  size: 2127384
  object_id: 2ff7a520-f3dd-487f-6af0-e7a7a8f758f3
  sha: sha256:3406a05b83a42231e3df68d02bc0a0cf47b3f2e8f11c8ede62267daf5f130016
freefont/freefont-otf-20120503.tar.gz:
  size: 4487813
  object_id: 8b483c1c-d553-48b3-500a-12c192782f73
  sha: dad7600fa9eed4116c2aaa561228e3879565f7aa
freetype/freetype-2.9.1.tar.gz:
  size: 2533956
  object_id: d74e6686-1bf9-46d4-7115-1b15aa2ca41c
  sha: 7498739e34e5dca4c61d05efdde6191ba69a2df0
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 65d1b23c-97f5-4555-719a-9c4c8cc1904f
  sha: e3c0618c2d2e5586eda9498c867d5e4858a3b0e2
grafana/grafana-8.5.15.linux-amd64.tar.gz:
  size: 79032031
  object_id: 9519f9cc-c09e-46e5-68e2-e105b8b906bc
  sha: sha256:98eac35b7da8ca9b74efcfd6ab519a01bc14d2222b2cf8a6cbd4520cc0a5f98b
grafana_plugins/flant-statusmap-panel-v0.4.2.zip:
  size: 286169
  object_id: 010ca6fc-4f4c-4d26-7663-3c73555c112b
  sha: sha256:c1673d40021d2f4a857a19cc7c8933f9d509cb4fb7ffc095a7242dc157baf819
grafana_plugins/grafana-clock-panel-v1.1.1.zip:
  size: 621739
  object_id: 9536cd55-c7d9-4f68-56a8-ab4b3f966eba
  sha: sha256:4af67283bafe5c6ea2ee3a98c31a4f9fa67325ceea9ad7cfb72a61629a544439
grafana_plugins/grafana-piechart-panel-v1.6.1.zip:
  size: 274360
  object_id: 1b54b9da-4c31-45af-50d5-2c94c1ced745
  sha: sha256:eb82bf79fa012ae045a7c270efd85374cc93bab4d9b0bd2a7e03c37145b3da38
grafana_plugins/grafana-worldmap-panel-v0.3.2.zip:
  size: 2681129
  object_id: 48b520b3-8b0a-4b7c-46dd-cd5656914928
  sha: sha256:306009cd2f57f75c7ac2ddf4e631f57212e85b7cddee92180f04673e0f6aae01
grafana_plugins/jdbranham-diagram-panel-v1.7.1.zip:
  size: 17352318
  object_id: 946d44a3-bc5f-494a-6246-a765899b3924
  sha: sha256:b4060059e31f02a015a177c17b71d4e3c6f7dfa3576a2f720e284ce026149ccc
grafana_plugins/mtanda-histogram-panel-v0.1.6.zip:
  size: 76062
  object_id: 52255f76-001d-4401-514b-d1ce42b82eb3
  sha: sha256:60495c5eca135fdc31530f299e2caab3389840ad8526e17a0c6e0d5934e6858b
grafana_plugins/vonage-status-panel-v1.0.10.zip:
  size: 401708
  object_id: 1d94c564-ce22-461d-6689-3d2a728fdc55
  sha: sha256:1d3ffa533def063f077415cb775bbd54ad4bd1b9f5bfe7e62250635b77dc5589
graphite_exporter/graphite_exporter-0.13.1.linux-amd64.tar.gz:
  size: 14924750
  object_id: fb5e8585-252a-42d0-4d21-a2c5515d049a
  sha: sha256:05e321161e65c9886226339bd589349103d5ee56aa68561f5a76937befe8130c
haproxy_exporter/haproxy_exporter-0.14.0.linux-amd64.tar.gz:
  size: 7896800
  object_id: fa45a227-f8af-4045-5f4c-b09cced20419
  sha: sha256:98e3fb3c2857ba001a5435c990360da5c0e409d65ca7f25599ed13e4e702058d
influxdb_exporter/influxdb_exporter-0.11.1.linux-amd64.tar.gz:
  size: 6952555
  object_id: e3407aaf-59de-4f3f-5837-ccb6b8e11372
  sha: sha256:ca46e647c854ebcbc51d8cf405c9530707ac2b00fe6a3263cb47434da1e7c703
ingestor_exporter/ingestor_exporter-2.2.0.linux-amd64.tar.gz:
  size: 5924704
  object_id: a0ce369b-0024-4b67-75ea-2bb51551d9b7
  sha: sha256:54be2bbc9f89ffbf8f70c476ec2b1835cbd619db94d18d1ae537c1a602e9b116
jq/jq-1.6.linux64:
  size: 3953824
  object_id: 04453e77-c1dd-40ad-49a8-54dedf95d8bf
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libxml2/libxml2-2.9.10.tar.gz:
  size: 5624761
  object_id: 03abdd76-bc8b-4884-7912-9b9f83462d1c
  sha: sha256:aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f
memcached_exporter/memcached_exporter-0.10.0.linux-amd64.tar.gz:
  size: 7305144
  object_id: 48223329-4230-47ae-50fd-f6cbb7b9eeca
  sha: sha256:f87540d148473733403ca3ac2adc14101ee229fe89d463b0f5763a0b258b1631
mongodb_exporter/mongodb_exporter-1.0.0.linux-amd64.tar.gz:
  size: 2873863
  object_id: 7d6b44a6-b6a3-4900-9671-979d984c2665
  sha: 073286f537e06dea8980a36818206b237e031d20
mysqld_exporter/mysqld_exporter-0.14.0.linux-amd64.tar.gz:
  size: 7450991
  object_id: 1daa0fd1-e981-49e5-5cc6-37ccd04602d6
  sha: sha256:c17402137a4e9745f593127f162c1003298910cb8aa7d05bee3384738de094ae
nats_exporter/nats_exporter-1.0.0.linux_amd64.tar.gz:
  size: 2492944
  object_id: f549cec1-4dab-413b-b5b0-183f18b90f7f
  sha: 8c3ce30c2a8d67d0f951bc3039a0b5c1a54cd536
nginx/nginx-1.21.6.tar.gz:
  size: 1073364
  object_id: 6deae91f-99fe-4b45-68b0-3f5acc434e6c
  sha: sha256:66dc7081488811e9f925719e34d1b4504c2801c81dee2920e5452a86b11405ae
nginx/pcre-8.45.tar.gz:
  size: 2096552
  object_id: 07d80377-8e45-4f83-7d5b-47c2df280efb
  sha: sha256:4e6ce03e0336e8b4a3d6c2b70b1c5e18590a5673a98186da90d4f33c23defc09
postgres_exporter/postgres_exporter-0.11.1.linux-amd64.tar.gz:
  size: 7809573
  object_id: 98af1667-7c8d-47bf-7c0d-79c2fa53a9a7
  sha: sha256:ec27e2a52b764c4313076ea6db335607cc40fb8a503dcb74d9517dc8baf049f0
prometheus/prometheus-1.8.2.linux-amd64.tar.gz:
  size: 17748716
  object_id: 54fd8c7b-a676-44cd-64b2-d5788552e607
  sha: 33101ac86a6376680c3b44b63db47f1754d77a1a
prometheus/prometheus-2.41.0.linux-amd64.tar.gz:
  size: 90331753
  object_id: 25b2b0e4-bebb-46fe-6306-8ea25d1b30fd
  sha: sha256:9c1486f5f3e03d56433112594740ca84c6e59db061d096eeb3ea971ba25441c9
pushgateway/pushgateway-1.5.1.linux-amd64.tar.gz:
  size: 10051993
  object_id: 34807b91-69fb-45fb-4469-bee3240f2cf6
  sha: sha256:3c1fb80e0e777fb98a9171c888adf9553bfab5a0b58af730ae108ac0970ec2a4
rabbitmq_exporter/rabbitmq_exporter-0.29.0.linux-amd64.tar.gz:
  size: 3604790
  object_id: 0034971e-2cbd-4fd1-638b-b990b36b08fa
  sha: fa1d46a83ecc094d0bddcf3d593008617eba5d18
redis_exporter/redis_exporter-v1.35.1.linux-amd64.tar.gz:
  size: 3235737
  object_id: 6fed2539-9c93-4129-66e1-eebd8ff2120c
  sha: sha256:0b4eaaa85d0887f5ebc7c44cd8d67485298ede19f1537a81f4f94eed2f75701b
shield_exporter/shield_exporter-0.3.0.linux-amd64.tar.gz:
  size: 3696892
  object_id: 479e7d54-3fc6-4822-53bf-0e16b57e45a9
  sha: 6f1f98f54e15212f3405309f52b7666770fc15e3
stackdriver_exporter/stackdriver_exporter-0.12.0.linux-amd64.tar.gz:
  size: 8685045
  object_id: 80e4df9a-7bc1-43bb-52de-35a74ef60266
  sha: sha256:de4e3f5b9ce39517ca9172011e3e3561ac34e1716947c357c4c720296f67b994
statsd_exporter/statsd_exporter-0.23.0.linux-amd64.tar.gz:
  size: 7747982
  object_id: e9797ea2-607d-4bb9-543f-30912192218d
  sha: sha256:1558c99d019ba9a9d6635068da5e7e8f04543544fb33c019fc869d0499ec7441
util-linux/util-linux-2.36.1.tar.gz:
  size: 11151380
  object_id: d148dc5e-357e-4f06-4261-c6cc5cc27d57
  sha: sha256:37de03dbb98cdeffdf9e754122b0aca2a9bbdc19769f6570dfcb6f123643bf53
vault_exporter/vault_exporter_0.1.2_linux_amd64.tar.gz:
  size: 3809657
  object_id: b57907a1-69f8-4e62-6708-e0e632b8ec32
  sha: 4c6e2770de08eedf96b33e9fde508d60c07aafe8
