---
builds:
  78d2ac8730f453308c4f2caf967867b46ab78dd6:
    version: 78d2ac8730f453308c4f2caf967867b46ab78dd6
    sha1: 1d8d3acf87ac11b144c5ef52e23139fa71f85e1e
    blobstore_id: 9d3fd7ae-fcf7-42ce-8a81-f84c7bf1c4ef
  3ddfffb5f68074dca70665e830c44414a019d21d:
    version: 3ddfffb5f68074dca70665e830c44414a019d21d
    sha1: f52fea422aa69cda58362877e5caa197deb6372f
    blobstore_id: 76fc6d58-bba5-454d-92e8-03567da66383
  8e408679c4ee0d8f4afbcf33354ebf1127c7f20f:
    version: 8e408679c4ee0d8f4afbcf33354ebf1127c7f20f
    sha1: b68ea3a6ffa90a3113d84886d4f63ba422f15893
    blobstore_id: aec25d4c-56a4-4718-a894-055613fe7d2e
  da03030405742ccfce719ff2765b11ae267da978:
    version: da03030405742ccfce719ff2765b11ae267da978
    sha1: 6d703e5c51bc40a907684bb5f210517d5523e684
    blobstore_id: b565e2a8-b173-4f0f-87b9-20a93e8378a3
  90d6d22f272a842109ddafab12c50452ab0db4c6:
    version: 90d6d22f272a842109ddafab12c50452ab0db4c6
    sha1: 8fa299f03bdf89fb6e483250ada74caf3b0e8f99
    blobstore_id: e39713b1-f4ee-4a59-906f-83ac3e080eb0
  2ab1d1ea80c539fde895968d05a11074d445d2a0:
    version: 2ab1d1ea80c539fde895968d05a11074d445d2a0
    sha1: caaa186bb26cdd5817cd498dac2ed06fd8769cc1
    blobstore_id: 83f0ae21-105e-4a49-8a71-5166731af267
  6489b420b590f718ff47e6a230d35473513c7aed:
    version: 6489b420b590f718ff47e6a230d35473513c7aed
    sha1: bc739fc804ac60f0b13d0b0e63b14446ae3bc574
    blobstore_id: f3b278c8-1043-4e01-b78c-952f9c4d9501
  bcb9533d05c3c6d1bf909cf762212163929d0c25:
    version: bcb9533d05c3c6d1bf909cf762212163929d0c25
    sha1: 0cbb47c5abe16e2b74107d78f6dfaf958b07e152
    blobstore_id: 207165ee-38a3-49c9-b540-e6797e924445
  4f6729c402ffaf524392162cde8bd1c9461490ed:
    version: 4f6729c402ffaf524392162cde8bd1c9461490ed
    sha1: 5c959ce98363e21074cf20a940574e7bf4130ce3
    blobstore_id: 792240a9-1bb1-49a3-a3c8-54a0941a8351
  ad2eae9292bb2c85480d004a5a6fbe07e6f7bbb4:
    version: ad2eae9292bb2c85480d004a5a6fbe07e6f7bbb4
    sha1: 6ab865081360aaae5c27d04cbc524da0cb39a6f1
    blobstore_id: 9ee25ee9-981b-41a6-a565-5b7e2ac38604
  a5dcf0fcf83cd83f62b08571006e0cf9867e036c:
    version: a5dcf0fcf83cd83f62b08571006e0cf9867e036c
    sha1: ce90eb83804133e416a4086952656096e151fb67
    blobstore_id: 6b666eac-8691-4e7f-89bc-3422037face9
format-version: '2'
